## Loading and Combining Datasets

In [10]:
import polars as pl
import pandas as pd
import polars.selectors as cs

In [11]:
all_df_filepath = r"..\data\temzy\all data .xlsx"

In [12]:
def load_and_comb_dfs(filepath: str)-> pl.DataFrame:
    try:
        comb_df = pl.read_excel(
            filepath,
            sheet_id=0,
            infer_schema_length=None,
        )

        all_dfs_list = []

        for name, sheet in comb_df.items():
            sheet = sheet.with_columns(pl.lit(name).alias('country'))
            all_dfs_list.append(sheet)
            
        df = pl.concat(all_dfs_list, how='diagonal')
        df = df.rename({'__UNNAMED__0': 'year'}).drop(df.columns[-1])
        return df
    except FileNotFoundError:
        print("Data file not found in directory! Kindly ensure file exists in folder path.")
    except Exception as e:
        print(f"Error encountered: {e}")

final_df = load_and_comb_dfs(filepath=all_df_filepath)
final_df.describe()
final_df

shape: (300, 9)
┌──────┬─────────────┬────────────┬────────────┬───┬───────────┬────────────┬────────────┬─────────┐
│ year ┆ Real GDP    ┆ Median     ┆ Unemployme ┆ … ┆ Inflation ┆ Imports    ┆ Exports    ┆ country │
│ ---  ┆ (USD        ┆ Disposable ┆ nt Rate (% ┆   ┆ ---       ┆ (USD       ┆ (USD       ┆ ---     │
│ i64  ┆ million) (% ┆ Income per ┆ of econom… ┆   ┆ f64       ┆ million)   ┆ million)   ┆ str     │
│      ┆ grow…       ┆ H…         ┆ ---        ┆   ┆           ┆ ---        ┆ ---        ┆         │
│      ┆ ---         ┆ ---        ┆ f64        ┆   ┆           ┆ f64        ┆ f64        ┆         │
│      ┆ f64         ┆ f64        ┆            ┆   ┆           ┆            ┆            ┆         │
╞══════╪═════════════╪════════════╪════════════╪═══╪═══════════╪════════════╪════════════╪═════════╡
│ 1993 ┆ 484743.6    ┆ 4189.9     ┆ 6.523      ┆ … ┆ 1956.415  ┆ 27604.4    ┆ 38554.8    ┆ Brazil  │
│ 1994 ┆ 604102.9    ┆ 5121.8     ┆ 6.72       ┆ … ┆ 2188.422  ┆ 36192.3    ┆ 43545.1    ┆ Brazil  │
│ 1995 ┆ 778788.9    ┆ 7651.9     ┆ 7.24       ┆ … ┆ 71.039    ┆ 54137.4    ┆ 46506.3    ┆ Brazil  │
│ 1996 ┆ 850426.4    ┆ 8312.4     ┆ 8.199      ┆ … ┆ 15.757    ┆ 56981.0    ┆ 47746.7    ┆ Brazil  │
│ 1997 ┆ 883207.8    ┆ 8428.1     ┆ 9.188      ┆ … ┆ 6.925     ┆ 64242.2    ┆ 52994.3    ┆ Brazil  │
│ …    ┆ …           ┆ …          ┆ …          ┆ … ┆ …         ┆ …          ┆ …          ┆ …       │
│ 2018 ┆ 245173.1    ┆ 4797.6     ┆ 2.002      ┆ … ┆ 3.539     ┆ 236868.9   ┆ 243698.7   ┆ Vietnam │
│ 2019 ┆ 261915.0    ┆ 5124.9     ┆ 2.163      ┆ … ┆ 2.795     ┆ 254092.8   ┆ 264340.8   ┆ Vietnam │
│ 2020 ┆ 271193.3    ┆ 5225.5     ┆ 2.455      ┆ … ┆ 3.22      ┆ 262673.3   ┆ 282528.8   ┆ Vietnam │
│ 2021 ┆ 288262.1    ┆ 5369.3     ┆ 3.145      ┆ … ┆ 1.835     ┆ 330742.7   ┆ 335824.6   ┆ Vietnam │
│ 2022 ┆ 303912.6    ┆ 5848.2     ┆ 2.345      ┆ … ┆ 3.216     ┆ 359181.2   ┆ 368603.0   ┆ Vietnam │
└──────┴─────────────┴────────────┴────────────┴───┴───────────┴────────────┴────────────┴─────────┘

In [13]:
clean_df = final_df.rename({
    'Real GDP (USD million) (% growth)': 'gdp_growth',
    'Median Disposable Income per Household (USD)': 'household_income',
    'Unemployment Rate (% of economically active population)': 'unemployment_rate',
    'Population Living Below International Poverty Line ($1.90 a Day)': 'poverty_rate',
    'Inflation': 'inflation',
    'Imports (USD million)': 'imports',
    'Exports (USD million)': 'exports'
})

# clean_df.sort(['country', 'year'])

In [14]:
clean_df

shape: (300, 9)
┌──────┬────────────┬───────────────┬──────────────┬───┬───────────┬──────────┬──────────┬─────────┐
│ year ┆ gdp_growth ┆ household_inc ┆ unemployment ┆ … ┆ inflation ┆ imports  ┆ exports  ┆ country │
│ ---  ┆ ---        ┆ ome           ┆ _rate        ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---     │
│ i64  ┆ f64        ┆ ---           ┆ ---          ┆   ┆ f64       ┆ f64      ┆ f64      ┆ str     │
│      ┆            ┆ f64           ┆ f64          ┆   ┆           ┆          ┆          ┆         │
╞══════╪════════════╪═══════════════╪══════════════╪═══╪═══════════╪══════════╪══════════╪═════════╡
│ 1993 ┆ 484743.6   ┆ 4189.9        ┆ 6.523        ┆ … ┆ 1956.415  ┆ 27604.4  ┆ 38554.8  ┆ Brazil  │
│ 1994 ┆ 604102.9   ┆ 5121.8        ┆ 6.72         ┆ … ┆ 2188.422  ┆ 36192.3  ┆ 43545.1  ┆ Brazil  │
│ 1995 ┆ 778788.9   ┆ 7651.9        ┆ 7.24         ┆ … ┆ 71.039    ┆ 54137.4  ┆ 46506.3  ┆ Brazil  │
│ 1996 ┆ 850426.4   ┆ 8312.4        ┆ 8.199        ┆ … ┆ 15.757    ┆ 56981.0  ┆ 47746.7  ┆ Brazil  │
│ 1997 ┆ 883207.8   ┆ 8428.1        ┆ 9.188        ┆ … ┆ 6.925     ┆ 64242.2  ┆ 52994.3  ┆ Brazil  │
│ …    ┆ …          ┆ …             ┆ …            ┆ … ┆ …         ┆ …        ┆ …        ┆ …       │
│ 2018 ┆ 245173.1   ┆ 4797.6        ┆ 2.002        ┆ … ┆ 3.539     ┆ 236868.9 ┆ 243698.7 ┆ Vietnam │
│ 2019 ┆ 261915.0   ┆ 5124.9        ┆ 2.163        ┆ … ┆ 2.795     ┆ 254092.8 ┆ 264340.8 ┆ Vietnam │
│ 2020 ┆ 271193.3   ┆ 5225.5        ┆ 2.455        ┆ … ┆ 3.22      ┆ 262673.3 ┆ 282528.8 ┆ Vietnam │
│ 2021 ┆ 288262.1   ┆ 5369.3        ┆ 3.145        ┆ … ┆ 1.835     ┆ 330742.7 ┆ 335824.6 ┆ Vietnam │
│ 2022 ┆ 303912.6   ┆ 5848.2        ┆ 2.345        ┆ … ┆ 3.216     ┆ 359181.2 ┆ 368603.0 ┆ Vietnam │
└──────┴────────────┴───────────────┴──────────────┴───┴───────────┴──────────┴──────────┴─────────┘

possible feature engineering
- export - import = trade_balance

### Log Dependent Var (Gdp Growth)

In [15]:
# clean_df = (clean_df
# .sort(['country', 'year'])
# .with_columns([
#    pl.col("gdp_growth").log().diff().over("country").alias('gdp_growth_log')
# ])
# )
# clean_df = clean_df.fill_null(0)

### Separate Collated DFs by Country

In [16]:
countries = clean_df.get_column("country").unique().to_list()

country_data = {
    country: clean_df.filter(pl.col("country") == country).sort("year")
    for country in countries
}

country_data

{'India': shape: (30, 9)
 ┌──────┬────────────┬───────────────┬──────────────┬───┬───────────┬──────────┬──────────┬─────────┐
 │ year ┆ gdp_growth ┆ household_inc ┆ unemployment ┆ … ┆ inflation ┆ imports  ┆ exports  ┆ country │
 │ ---  ┆ ---        ┆ ome           ┆ _rate        ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---     │
 │ i64  ┆ f64        ┆ ---           ┆ ---          ┆   ┆ f64       ┆ f64      ┆ f64      ┆ str     │
 │      ┆            ┆ f64           ┆ f64          ┆   ┆           ┆          ┆          ┆         │
 ╞══════╪════════════╪═══════════════╪══════════════╪═══╪═══════════╪══════════╪══════════╪═════════╡
 │ 1993 ┆ 287273.8   ┆ 1120.4        ┆ 5.612        ┆ … ┆ 6.362     ┆ 22788.4  ┆ 21571.6  ┆ India   │
 │ 1994 ┆ 327525.5   ┆ 1277.2        ┆ 5.631        ┆ … ┆ 10.212    ┆ 26842.7  ┆ 25021.8  ┆ India   │
 │ 1995 ┆ 371782.7   ┆ 1396.7        ┆ 5.636        ┆ … ┆ 10.225    ┆ 34706.9  ┆ 30630.0  ┆ India   │
 │ 1996 ┆ 393646.9   ┆ 1472.3        ┆ 5.652        ┆ … ┆ 8.977     ┆ 37942.2  ┆ 33105.1  ┆ India   │
 │ 1997 ┆ 425545.0   ┆ 1587.7        ┆ 5.637        ┆ … ┆ 7.164     ┆ 41431.9  ┆ 35008.1  ┆ India   │
 │ …    ┆ …          ┆ …             ┆ …            ┆ … ┆ …         ┆ …        ┆ …        ┆ …       │
 │ 2018 ┆ 2762974.5  ┆ 5798.8        ┆ 5.33         ┆ … ┆ 4.861     ┆ 513147.7 ┆ 325046.5 ┆ India   │
 │ 2019 ┆ 2850709.5  ┆ 5895.4        ┆ 5.358        ┆ … ┆ 7.66      ┆ 485250.2 ┆ 324296.6 ┆ India   │
 │ 2020 ┆ 2672068.5  ┆ 5366.6        ┆ 6.48         ┆ … ┆ 5.561     ┆ 369312.7 ┆ 275951.8 ┆ India   │
 │ 2021 ┆ 3200522.1  ┆ 6156.4        ┆ 6.12         ┆ … ┆ 4.89      ┆ 573494.1 ┆ 394776.5 ┆ India   │
 │ 2022 ┆ 3402271.2  ┆ 6710.7        ┆ 5.848        ┆ … ┆ 5.9       ┆ 728687.1 ┆ 456478.4 ┆ India   │
 └──────┴────────────┴───────────────┴──────────────┴───┴───────────┴──────────┴──────────┴─────────┘,
 'Brazil': shape: (30, 9)
 ┌──────┬────────────┬───────────────┬──────────────┬───┬───────────┬──────────┬──────────┬─────────┐
 │ year ┆ gdp_growth ┆ household_inc ┆ unemployment ┆ … ┆ inflation ┆ imports  ┆ exports  ┆ country │
 │ ---  ┆ ---        ┆ ome           ┆ _rate        ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---     │
 │ i64  ┆ f64        ┆ ---           ┆ ---          ┆   ┆ f64       ┆ f64      ┆ f64      ┆ str     │
 │      ┆            ┆ f64           ┆ f64          ┆   ┆           ┆          ┆          ┆         │
 ╞══════╪════════════╪═══════════════╪══════════════╪═══╪═══════════╪══════════╪══════════╪═════════╡
 │ 1993 ┆ 484743.6   ┆ 4189.9        ┆ 6.523        ┆ … ┆ 1956.415  ┆ 27604.4  ┆ 38554.8  ┆ Brazil  │
 │ 1994 ┆ 604102.9   ┆ 5121.8        ┆ 6.72         ┆ … ┆ 2188.422  ┆ 36192.3  ┆ 43545.1  ┆ Brazil  │
 │ 1995 ┆ 778788.9   ┆ 7651.9        ┆ 7.24         ┆ … ┆ 71.039    ┆ 54137.4  ┆ 46506.3  ┆ Brazil  │
 │ 1996 ┆ 850426.4   ┆ 8312.4        ┆ 8.199        ┆ … ┆ 15.757    ┆ 56981.0  ┆ 47746.7  ┆ Brazil  │
 │ 1997 ┆ 883207.8   ┆ 8428.1        ┆ 9.188        ┆ … ┆ 6.925     ┆ 64242.2  ┆ 52994.3  ┆ Brazil  │
 │ …    ┆ …          ┆ …             ┆ …            ┆ … ┆ …         ┆ …        ┆ …        ┆ …       │
 │ 2018 ┆ 1917163.8  ┆ 13524.5       ┆ 12.375       ┆ … ┆ 3.665     ┆ 185322.0 ┆ 231889.5 ┆ Brazil  │
 │ 2019 ┆ 1873623.9  ┆ 12033.2       ┆ 11.975       ┆ … ┆ 3.733     ┆ 185928.0 ┆ 221126.8 ┆ Brazil  │
 │ 2020 ┆ 1475668.6  ┆ 10232.0       ┆ 13.775       ┆ … ┆ 3.212     ┆ 158786.8 ┆ 209180.2 ┆ Brazil  │
 │ 2021 ┆ 1648315.2  ┆ 10634.4       ┆ 13.2         ┆ … ┆ 8.302     ┆ 219408.0 ┆ 280814.6 ┆ Brazil  │
 │ 2022 ┆ 1907380.9  ┆ 12672.8       ┆ 9.506        ┆ … ┆ 9.28      ┆ 272701.7 ┆ 334463.1 ┆ Brazil  │
 └──────┴────────────┴───────────────┴──────────────┴───┴───────────┴──────────┴──────────┴─────────┘,
 'Vietnam': shape: (30, 9)
 ┌──────┬────────────┬───────────────┬──────────────┬───┬───────────┬──────────┬──────────┬─────────┐
 │ year ┆ gdp_growth ┆ household_inc ┆ unemployment ┆ … ┆ inflation ┆ imports  ┆ exports  ┆ country │
 │ ---  ┆ ---        ┆ ome           ┆ _rate        ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---     │
 │ i64  ┆ f64        ┆ ---           ┆ ---          ┆   ┆ f64       ┆ f64      ┆ f64      ┆ str     │
 │      ┆            ┆ f64           ┆ f64          ┆   ┆           ┆          ┆          ┆         │
 ╞══════╪════════════╪═══════════════╪══════════════╪═══╪═══════════╪══════════╪══════════╪═════════╡
 │ 1993 ┆ 13180.9    ┆ 635.4         ┆ 2.007        ┆ … ┆ 8.379     ┆ 3923.9   ┆ 2985.2   ┆ Vietnam │
 │ 1994 ┆ 16281.1    ┆ 750.1         ┆ 2.023        ┆ … ┆ 9.488     ┆ 5825.8   ┆ 4054.3   ┆ Vietnam │
 │ 1995 ┆ 20736.2    ┆ 916.3         ┆ 2.061        ┆ … ┆ 16.93     ┆ 8155.4   ┆ 5448.9   ┆ Vietnam │
 │ 1996 ┆ 24657.5    ┆ 1055.8        ┆ 2.069        ┆ … ┆ 5.675     ┆ 11143.6  ┆ 7255.8   ┆ Vietnam │
 │ 1997 ┆ 26843.7    ┆ 1078.1        ┆ 3.075        ┆ … ┆ 3.21      ┆ 11592.3  ┆ 9185.0   ┆ Vietnam │
 │ …    ┆ …          ┆ …             ┆ …            ┆ … ┆ …         ┆ …        ┆ …        ┆ …       │
 │ 2018 ┆ 245173.1   ┆ 4797.6        ┆ 2.002        ┆ … ┆ 3.539     ┆ 236868.9 ┆ 243698.7 ┆ Vietnam │
 │ 2019 ┆ 261915.0   ┆ 5124.9        ┆ 2.163        ┆ … ┆ 2.795     ┆ 254092.8 ┆ 264340.8 ┆ Vietnam │
 │ 2020 ┆ 271193.3   ┆ 5225.5        ┆ 2.455        ┆ … ┆ 3.22      ┆ 262673.3 ┆ 282528.8 ┆ Vietnam │
 │ 2021 ┆ 288262.1   ┆ 5369.3        ┆ 3.145        ┆ … ┆ 1.835     ┆ 330742.7 ┆ 335824.6 ┆ Vietnam │
 │ 2022 ┆ 303912.6   ┆ 5848.2        ┆ 2.345        ┆ … ┆ 3.216     ┆ 359181.2 ┆ 368603.0 ┆ Vietnam │
 └──────┴────────────┴───────────────┴──────────────┴───┴───────────┴──────────┴──────────┴─────────┘,
 'Canada': shape: (30, 9)
 ┌──────┬────────────┬───────────────┬──────────────┬───┬───────────┬──────────┬──────────┬─────────┐
 │ year ┆ gdp_growth ┆ household_inc ┆ unemployment ┆ … ┆ inflation ┆ imports  ┆ exports  ┆ country │
 │ ---  ┆ ---        ┆ ome           ┆ _rate        ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---     │
 │ i64  ┆ f64        ┆ ---           ┆ ---          ┆   ┆ f64       ┆ f64      ┆ f64      ┆ str     │
 │      ┆            ┆ f64           ┆ f64          ┆   ┆           ┆          ┆          ┆         │
 ╞══════╪════════════╪═══════════════╪══════════════╪═══╪═══════════╪══════════╪══════════╪═════════╡
 │ 1993 ┆ 579067.0   ┆ 28369.5       ┆ 11.357       ┆ … ┆ 1.841     ┆ 139035.0 ┆ 145178.0 ┆ Canada  │
 │ 1994 ┆ 579927.4   ┆ 26858.8       ┆ 10.377       ┆ … ┆ 0.185     ┆ 155072.0 ┆ 165376.0 ┆ Canada  │
 │ 1995 ┆ 605943.4   ┆ 26957.8       ┆ 9.472        ┆ … ┆ 2.168     ┆ 168041.0 ┆ 192203.0 ┆ Canada  │
 │ 1996 ┆ 630621.9   ┆ 27144.7       ┆ 9.603        ┆ … ┆ 1.571     ┆ 174959.0 ┆ 201640.0 ┆ Canada  │
 │ 1997 ┆ 654999.9   ┆ 27163.9       ┆ 9.085        ┆ … ┆ 1.621     ┆ 200864.0 ┆ 214414.0 ┆ Canada  │
 │ …    ┆ …          ┆ …             ┆ …            ┆ … ┆ …         ┆ …        ┆ …        ┆ …       │
 │ 2018 ┆ 1725381.9  ┆ 50368.2       ┆ 5.842        ┆ … ┆ 2.268     ┆ 459807.7 ┆ 450828.1 ┆ Canada  │
 │ 2019 ┆ 1743560.3  ┆ 50721.0       ┆ 5.692        ┆ … ┆ 1.949     ┆ 453615.9 ┆ 446176.0 ┆ Canada  │
 │ 2020 ┆ 1647679.8  ┆ 53959.2       ┆ 9.692        ┆ … ┆ 0.717     ┆ 406051.4 ┆ 391007.1 ┆ Canada  │
 │ 2021 ┆ 2001486.7  ┆ 59015.1       ┆ 7.542        ┆ … ┆ 3.395     ┆ 489657.1 ┆ 503782.7 ┆ Canada  │
 │ 2022 ┆ 2.145532e6 ┆ 61566.2       ┆ 5.3          ┆ … ┆ 6.803     ┆ 572502.6 ┆ 598852.4 ┆ Canada  │
 └──────┴────────────┴───────────────┴──────────────┴───┴───────────┴──────────┴──────────┴─────────┘,
 'South Africa': shape: (30, 9)
 ┌──────┬────────────┬───────────────┬──────────────┬───┬───────────┬──────────┬──────────┬─────────┐
 │ year ┆ gdp_growth ┆ household_inc ┆ unemployment ┆ … ┆ inflation ┆ imports  ┆ exports  ┆ country │
 │ ---  ┆ ---        ┆ ome           ┆ _rate        ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---     │
 │ i64  ┆ f64        ┆ ---           ┆ ---          ┆   ┆ f64       ┆ f64      ┆ f64      ┆ str     │
 │      ┆            ┆ f64           ┆ f64          ┆   ┆           ┆          ┆          ┆         │
 ╞══════╪════════════╪═══════════════╪══════════════╪═══╪═══════════╪══════════╪══════════╪═════════╡
 │ 1993 ┆ 147194.8   ┆ 5792.1        ┆ 25.066       ┆ … ┆ 9.717     ┆ 19991.2  ┆ 24221.6  ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 │ 1994 ┆ 153512.7   ┆ 5824.6        ┆ 25.888       ┆ … ┆ 8.939     ┆ 23362.8  ┆ 25308.0  ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 │ 1995 ┆ 171735.9   ┆ 6201.0        ┆ 18.661       ┆ … ┆ 8.68      ┆ 30545.6  ┆ 27853.1  ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 │ 1996 ┆ 163234.9   ┆ 5550.8        ┆ 22.959       ┆ … ┆ 7.354     ┆ 30181.7  ┆ 29221.4  ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 │ 1997 ┆ 168978.1   ┆ 5767.7        ┆ 24.882       ┆ … ┆ 8.598     ┆ 32998.0  ┆ 31027.2  ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 │ …    ┆ …          ┆ …             ┆ …            ┆ … ┆ …         ┆ …        ┆ …        ┆ …       │
 │ 2018 ┆ 403945.8   ┆ 6728.5        ┆ 27.125       ┆ … ┆ 4.517     ┆ 93316.3  ┆ 94206.0  ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 │ 2019 ┆ 388462.9   ┆ 6279.7        ┆ 28.7         ┆ … ┆ 4.12      ┆ 88123.0  ┆ 89890.2  ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 │ 2020 ┆ 337843.3   ┆ 5303.6        ┆ 29.175       ┆ … ┆ 3.21      ┆ 68796.6  ┆ 85689.9  ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 │ 2021 ┆ 418684.6   ┆ 6275.3        ┆ 34.3         ┆ … ┆ 4.612     ┆ 93376.7  ┆ 123640.1 ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 │ 2022 ┆ 405404.2   ┆ 6038.8        ┆ 33.796       ┆ … ┆ 7.04      ┆ 110717.3 ┆ 123762.2 ┆ South   │
 │      ┆            ┆               ┆              ┆   ┆           ┆          ┆          ┆ Africa  │
 └──────┴────────────┴───────────────┴──────────────┴───┴───────────┴──────────┴──────────┴─────────┘,
 'Mexico': shape: (30, 9)
 ┌──────┬────────────┬───────────────┬──────────────┬───┬───────────┬──────────┬──────────┬─────────┐
 │ year ┆ gdp_growth ┆ household_inc ┆ unemployment ┆ … ┆ inflation ┆ imports  ┆ exports  ┆ country │
 │ ---  ┆ ---        ┆ ome           ┆ _rate        ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---     │
 │ i64  ┆ f64        ┆ ---           ┆ ---          ┆   ┆ f64       ┆ f64      ┆ f64      ┆ str     │
 │      ┆            ┆ f64           ┆ f64          ┆   ┆           ┆          ┆          ┆         │
 ╞══════╪════════════╪═══════════════╪══════════════╪═══╪═══════════╪══════════╪══════════╪═════════╡
 │ 1993 ┆ 500732.9   ┆ 12293.9       ┆ 6.671        ┆ … ┆ 9.752     ┆ 68438.8  ┆ 51886.0  ┆ Mexico  │
 │ 1994 ┆ 527810.1   ┆ 12065.3       ┆ 6.66         ┆ … ┆ 6.966     ┆ 83075.2  ┆ 60882.2  ┆ Mexico  │
 │ 1995 ┆ 360072.8   ┆ 7373.8        ┆ 6.764        ┆ … ┆ 34.999    ┆ 75858.3  ┆ 79541.6  ┆ Mexico  │
 │ 1996 ┆ 410972.9   ┆ 8684.6        ┆ 5.155        ┆ … ┆ 34.378    ┆ 93673.8  ┆ 95999.7  ┆ Mexico  │
 │ 1997 ┆ 500416.0   ┆ 10045.0       ┆ 3.957        ┆ … ┆ 20.627    ┆ 114847.0 ┆ 110431.0 ┆ Mexico  │
 │ …    ┆ …          ┆ …             ┆ …            ┆ … ┆ …         ┆ …        ┆ …        ┆ …       │
 │ 2018 ┆ 1222116.3  ┆ 18573.9       ┆ 3.32         ┆ … ┆ 4.899     ┆ 464302.4 ┆ 450712.7 ┆ Mexico  │
 │ 2019 ┆ 1269524.3  ┆ 19537.6       ┆ 3.49         ┆ … ┆ 3.636     ┆ 455241.6 ┆ 460603.7 ┆ Mexico  │
 │ 2020 ┆ 1089903.5  ┆ 16948.8       ┆ 4.432        ┆ … ┆ 3.397     ┆ 382985.9 ┆ 416999.4 ┆ Mexico  │
 │ 2021 ┆ 1271942.1  ┆ 20548.7       ┆ 4.139        ┆ … ┆ 5.689     ┆ 505715.6 ┆ 494224.5 ┆ Mexico  │
 │ 2022 ┆ 1418543.3  ┆ 23078.2       ┆ 3.25         ┆ … ┆ 8.072     ┆ 607114.4 ┆ 581016.7 ┆ Mexico  │
 └──────┴────────────┴───────────────┴──────────────┴───┴───────────┴──────────┴──────────┴─────────┘,
 'Egypt': shape: (30, 9)
 ┌──────┬────────────┬────────────────┬───────────────┬───┬───────────┬─────────┬─────────┬─────────┐
 │ year ┆ gdp_growth ┆ household_inco ┆ unemployment_ ┆ … ┆ inflation ┆ imports ┆ exports ┆ country │
 │ ---  ┆ ---        ┆ me             ┆ rate          ┆   ┆ ---       ┆ ---     ┆ ---     ┆ ---     │
 │ i64  ┆ f64        ┆ ---            ┆ ---           ┆   ┆ f64       ┆ f64     ┆ f64     ┆ str     │
 │      ┆            ┆ f64            ┆ f64           ┆   ┆           ┆         ┆         ┆         │
 ╞══════╪════════════╪════════════════╪═══════════════╪═══╪═══════════╪═════════╪═════════╪═════════╡
 │ 1993 ┆ 49267.1    ┆ 2605.0         ┆ 10.34         ┆ … ┆ 12.09     ┆ 8184.2  ┆ 2243.9  ┆ Egypt   │
 │ 1994 ┆ 54357.7    ┆ 2913.7         ┆ 10.355        ┆ … ┆ 8.154     ┆ 10185.1 ┆ 3463.3  ┆ Egypt   │
 │ 1995 ┆ 63233.4    ┆ 3440.1         ┆ 10.456        ┆ … ┆ 15.742    ┆ 11738.8 ┆ 3434.7  ┆ Egypt   │
 │ 1996 ┆ 71122.0    ┆ 4052.6         ┆ 9.193         ┆ … ┆ 7.187     ┆ 13018.6 ┆ 3534.5  ┆ Egypt   │
 │ 1997 ┆ 79805.2    ┆ 4566.7         ┆ 7.93          ┆ … ┆ 4.626     ┆ 13211.1 ┆ 3920.6  ┆ Egypt   │
 │ …    ┆ …          ┆ …              ┆ …             ┆ … ┆ …         ┆ …       ┆ …       ┆ …       │
 │ 2018 ┆ 261887.0   ┆ 7048.3         ┆ 9.846         ┆ … ┆ 14.406    ┆ 71309.4 ┆ 27510.0 ┆ Egypt   │
 │ 2019 ┆ 332754.4   ┆ 8441.7         ┆ 7.849         ┆ … ┆ 9.146     ┆ 71295.0 ┆ 28856.0 ┆ Egypt   │
 │ 2020 ┆ 389188.0   ┆ 10014.6        ┆ 7.963         ┆ … ┆ 5.045     ┆ 59854.0 ┆ 26646.0 ┆ Egypt   │
 │ 2021 ┆ 424535.7   ┆ 11014.6        ┆ 7.392         ┆ … ┆ 5.218     ┆ 73320.0 ┆ 40381.0 ┆ Egypt   │
 │ 2022 ┆ 407568.9   ┆ 10002.8        ┆ 7.234         ┆ … ┆ 13.896    ┆ 82877.5 ┆ 48618.4 ┆ Egypt   │
 └──────┴────────────┴────────────────┴───────────────┴───┴───────────┴─────────┴─────────┴─────────┘,
 'Germany': shape: (30, 9)
 ┌──────┬────────────┬──────────────┬─────────────┬───┬───────────┬───────────┬───────────┬─────────┐
 │ year ┆ gdp_growth ┆ household_in ┆ unemploymen ┆ … ┆ inflation ┆ imports   ┆ exports   ┆ country │
 │ ---  ┆ ---        ┆ come         ┆ t_rate      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---     │
 │ i64  ┆ f64        ┆ ---          ┆ ---         ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str     │
 │      ┆            ┆ f64          ┆ f64         ┆   ┆           ┆           ┆           ┆         │
 ╞══════╪════════════╪══════════════╪═════════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
 │ 1993 ┆ 2050292.1  ┆ 32251.2      ┆ 7.847       ┆ … ┆ 4.435     ┆ 346027.0  ┆ 382472.0  ┆ Germany │
 │ 1994 ┆ 2176286.9  ┆ 33185.3      ┆ 8.923       ┆ … ┆ 2.745     ┆ 385351.0  ┆ 429722.0  ┆ Germany │
 │ 1995 ┆ 2478169.3  ┆ 37126.2      ┆ 8.341       ┆ … ┆ 1.724     ┆ 464271.0  ┆ 523802.0  ┆ Germany │
 │ 1996 ┆ 2.439671e6 ┆ 36497.9      ┆ 9.022       ┆ … ┆ 1.446     ┆ 458783.0  ┆ 524198.0  ┆ Germany │
 │ 1997 ┆ 2224022.8  ┆ 32891.9      ┆ 10.084      ┆ … ┆ 1.88      ┆ 445616.0  ┆ 512427.0  ┆ Germany │
 │ …    ┆ …          ┆ …            ┆ …           ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
 │ 2018 ┆ 3972624.9  ┆ 49582.6      ┆ 3.208       ┆ … ┆ 1.732     ┆ 1261750.7 ┆ 1525145.2 ┆ Germany │
 │ 2019 ┆ 3888174.6  ┆ 48004.9      ┆ 2.975       ┆ … ┆ 1.446     ┆ 1218440.7 ┆ 1459610.6 ┆ Germany │
 │ 2020 ┆ 3880941.6  ┆ 49296.5      ┆ 3.625       ┆ … ┆ 0.507     ┆ 1138843.5 ┆ 1356812.8 ┆ Germany │
 │ 2021 ┆ 4260527.4  ┆ 52423.2      ┆ 3.575       ┆ … ┆ 3.143     ┆ 1390116.8 ┆ 1621439.3 ┆ Germany │
 │ 2022 ┆ 4066659.8  ┆ 51657.6      ┆ 3.033       ┆ … ┆ 7.904     ┆ 1518349.6 ┆ 1639166.6 ┆ Germany │
 └──────┴────────────┴──────────────┴─────────────┴───┴───────────┴───────────┴───────────┴─────────┘,
 'Czech Republic': shape: (30, 9)
 ┌──────┬────────────┬─────────────┬─────────────┬───┬───────────┬──────────┬──────────┬────────────┐
 │ year ┆ gdp_growth ┆ household_i ┆ unemploymen ┆ … ┆ inflation ┆ imports  ┆ exports  ┆ country    │
 │ ---  ┆ ---        ┆ ncome       ┆ t_rate      ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---        │
 │ i64  ┆ f64        ┆ ---         ┆ ---         ┆   ┆ f64       ┆ f64      ┆ f64      ┆ str        │
 │      ┆            ┆ f64         ┆ f64         ┆   ┆           ┆          ┆          ┆            │
 ╞══════╪════════════╪═════════════╪═════════════╪═══╪═══════════╪══════════╪══════════╪════════════╡
 │ 1993 ┆ 40867.0    ┆ 4496.8      ┆ 4.319       ┆ … ┆ 20.8      ┆ 15518.2  ┆ 14466.3  ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 │ 1994 ┆ 47850.0    ┆ 5339.3      ┆ 4.297       ┆ … ┆ 9.865     ┆ 18259.6  ┆ 16230.4  ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 │ 1995 ┆ 60145.6    ┆ 7025.9      ┆ 4.024       ┆ … ┆ 9.465     ┆ 26384.7  ┆ 21686.1  ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 │ 1996 ┆ 67388.5    ┆ 7901.7      ┆ 3.895       ┆ … ┆ 8.819     ┆ 29366.1  ┆ 21915.6  ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 │ 1997 ┆ 62180.6    ┆ 7517.4      ┆ 4.272       ┆ … ┆ 8.548     ┆ 28837.1  ┆ 22746.5  ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 │ …    ┆ …          ┆ …           ┆ …           ┆ … ┆ …         ┆ …        ┆ …        ┆ …          │
 │ 2018 ┆ 248995.8   ┆ 27046.8     ┆ 2.267       ┆ … ┆ 2.142     ┆ 161918.7 ┆ 166590.0 ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 │ 2019 ┆ 252548.2   ┆ 27233.2     ┆ 2.017       ┆ … ┆ 2.842     ┆ 154621.1 ┆ 160975.9 ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 │ 2020 ┆ 245912.9   ┆ 27463.3     ┆ 2.55        ┆ … ┆ 3.156     ┆ 142927.7 ┆ 150913.4 ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 │ 2021 ┆ 281698.7   ┆ 31418.9     ┆ 2.808       ┆ … ┆ 3.854     ┆ 182468.0 ┆ 182087.8 ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 │ 2022 ┆ 293419.0   ┆ 33475.8     ┆ 2.4         ┆ … ┆ 15.103    ┆ 201593.5 ┆ 192604.6 ┆ Czech      │
 │      ┆            ┆             ┆             ┆   ┆           ┆          ┆          ┆ Republic   │
 └──────┴────────────┴─────────────┴─────────────┴───┴───────────┴──────────┴──────────┴────────────┘,
 'Colombia': shape: (30, 9)
 ┌──────┬────────────┬───────────────┬───────────────┬───┬───────────┬─────────┬─────────┬──────────┐
 │ year ┆ gdp_growth ┆ household_inc ┆ unemployment_ ┆ … ┆ inflation ┆ imports ┆ exports ┆ country  │
 │ ---  ┆ ---        ┆ ome           ┆ rate          ┆   ┆ ---       ┆ ---     ┆ ---     ┆ ---      │
 │ i64  ┆ f64        ┆ ---           ┆ ---           ┆   ┆ f64       ┆ f64     ┆ f64     ┆ str      │
 │      ┆            ┆ f64           ┆ f64           ┆   ┆           ┆         ┆         ┆          │
 ╞══════╪════════════╪═══════════════╪═══════════════╪═══╪═══════════╪═════════╪═════════╪══════════╡
 │ 1993 ┆ 71746.0    ┆ 5104.3        ┆ 5.039         ┆ … ┆ 22.438    ┆ 9831.5  ┆ 7115.9  ┆ Colombia │
 │ 1994 ┆ 94692.9    ┆ 6358.4        ┆ 4.915         ┆ … ┆ 22.848    ┆ 11882.9 ┆ 8478.9  ┆ Colombia │
 │ 1995 ┆ 109579.7   ┆ 6827.4        ┆ 5.65          ┆ … ┆ 20.894    ┆ 13852.9 ┆ 10125.8 ┆ Colombia │
 │ 1996 ┆ 115081.6   ┆ 6550.0        ┆ 7.802         ┆ … ┆ 20.798    ┆ 13683.6 ┆ 10587.0 ┆ Colombia │
 │ 1997 ┆ 126363.2   ┆ 6719.3        ┆ 7.902         ┆ … ┆ 18.468    ┆ 15377.7 ┆ 11522.4 ┆ Colombia │

# Diagnostics and Validation

In [17]:
import polars as pl
import numpy as np
import pandas as pd
import statsmodels.api as sm

from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.stats.diagnostic import het_breuschpagan, het_white
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.anova import anova_lm

## Stationarity
- Logarithmic differencing is applied to all float variables to convert them into growth rates, ensuring stationarity, reducing trends, and maintaining consistency across the dataset.
 
- It was previously applied only to specific columns in the previous version.
  - gdp_growth, household_income, exports and imports
(14-04-2026)

Further actions: (27-04-2026) 
  + Log only normal continous data, leave rates (unemployment, poverty and inflation) unlogged.
  + you can apply differencing only if possible.

**Date Last Modified: 27-04-2026**

### Functions

In [18]:
import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, kpss

def clean_series(series):
    s = pd.Series(series)
    s = s.replace([np.inf, -np.inf], np.nan).dropna()
    return s

def run_adf(series, name="variable"):
    series = clean_series(series)

    if len(series) < 3:
        return {
            "variable": name,
            "test": "ADF",
            "statistic": np.nan,
            "p_value": np.nan,
            "lags_used": np.nan,
            "n_obs": len(series),
            "note": "Too few observations"
        }

    if series.nunique() <= 1 or np.isclose(series.std(ddof=0), 0, equal_nan=True):
        return {
            "variable": name,
            "test": "ADF",
            "statistic": np.nan,
            "p_value": np.nan,
            "lags_used": np.nan,
            "n_obs": len(series),
            "note": "Constant / invalid series"
        }

    try:
        result = adfuller(series)
        return {
            "variable": name,
            "test": "ADF",
            "statistic": result[0],
            "p_value": result[1],
            "lags_used": result[2],
            "n_obs": result[3],
            "note": ""
        }
    except Exception as e:
        return {
            "variable": name,
            "test": "ADF",
            "statistic": np.nan,
            "p_value": np.nan,
            "lags_used": np.nan,
            "n_obs": len(series),
            "note": str(e)
        }

def run_kpss(series, name="variable"):
    series = clean_series(series)

    if len(series) < 3:
        return {
            "variable": name,
            "test": "KPSS",
            "statistic": np.nan,
            "p_value": np.nan,
            "lags_used": np.nan,
            "note": "Too few observations"
        }

    if series.nunique() <= 1 or np.isclose(series.std(ddof=0), 0, equal_nan=True):
        return {
            "variable": name,
            "test": "KPSS",
            "statistic": np.nan,
            "p_value": np.nan,
            "lags_used": np.nan,
            "note": "Constant / invalid series"
        }

    try:
        result = kpss(series, regression="c", nlags="auto")
        return {
            "variable": name,
            "test": "KPSS",
            "statistic": result[0],
            "p_value": result[1],
            "lags_used": result[2],
            "note": ""
        }
    except Exception as e:
        return {
            "variable": name,
            "test": "KPSS",
            "statistic": np.nan,
            "p_value": np.nan,
            "lags_used": np.nan,
            "note": str(e)
        }

def stationarity_check(variables: list, data_dict) -> pl.dataframe:
    stationarity_results = []

    for country, data in data_dict.items():
        for col in variables:
            values = data.get_column(col).to_list()

            adf_result = run_adf(values, col)
            adf_result['statistic'] = round(adf_result['statistic'],3)
            adf_result['p_value'] = round(adf_result['p_value'],3)
            adf_result["country"] = country
            stationarity_results.append(adf_result)

            kpss_result = run_kpss(values, col)
            kpss_result['statistic'] = round(kpss_result['statistic'], 3)
            kpss_result['p_value'] = round(kpss_result['p_value'], 3)
            kpss_result["country"] = country
            stationarity_results.append(kpss_result)

    stationarity_df = pl.DataFrame(stationarity_results)
    return stationarity_df

def statinarity_data_transformation(data_dict: dict) -> dict:
    trans_data_dict = {}

    try:
        for country, data in data_dict.items():
            
            df = (
                data
                .sort("year")
                .with_columns(
                    cs.float().cast(pl.Float64).log().diff()
            )
                .drop_nulls(
                    cs.float()
                )
            )
            
            trans_data_dict[country] = df

        return trans_data_dict
    except Exception as e:
        print(f"Error encountered: {e}")

### Raw DF Stationarity Check

In [19]:
raw_df_variables = ["gdp_growth", "household_income", "unemployment_rate", "poverty_rate", "inflation", "imports", "exports"]

raw_df_stationarity_check = stationarity_check(variables=raw_df_variables, data_dict=country_data)

C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")

In [20]:
ad = raw_df_stationarity_check
ac = ad.to_pandas()
ac.to_csv(r"..\data\ecoms_results\raw_data_stationarity_check.csv", index=False)

In [21]:
stationarity_pd = ad.to_pandas()

decision_map = {}

for country in countries:
    decision_map[country] = {}
    for var in raw_df_variables:
        adf_p = stationarity_pd[
            (stationarity_pd["country"] == country) &
            (stationarity_pd["variable"] == var) &
            (stationarity_pd["test"] == "ADF")
        ]["p_value"].iloc[0]

        kpss_p = stationarity_pd[
            (stationarity_pd["country"] == country) &
            (stationarity_pd["variable"] == var) &
            (stationarity_pd["test"] == "KPSS")
        ]["p_value"].iloc[0]

        decision_map[country][var] = {
            "difference": (adf_p > 0.05) or (kpss_p < 0.05),
            "adf_p": adf_p,
            "kpss_p": kpss_p
        }

### Transformation
- logarithmic differencing was applied to all float columns

Observation
- Applying logarithmic differencing to all columns affected variables like poverty with -inf and zero values when calculating kpss stationarity especially for country like Czech Republic with 0.0 poverty rates.
- Modified the ADF and KPSS functions to account for this anomaly. 

Recommendation
- Ask Temzy for further actions.

In [22]:
transformed_data = statinarity_data_transformation(data_dict=country_data)
transformed_data['Canada'].columns

['year',
 'gdp_growth',
 'household_income',
 'unemployment_rate',
 'poverty_rate',
 'inflation',
 'imports',
 'exports',
 'country']

#### Identifying country with Nan after transformation

In [23]:
variables = ["gdp_growth", "household_income", "unemployment_rate", "poverty_rate", "inflation", "imports", "exports"]

for country, df in transformed_data.items():
    print(f"\n--- {country} ---")
    for col in variables:
        s = df.get_column(col).to_pandas().dropna()
        print(col, "len=", len(s), "nunique=", s.nunique(), "std=", round(s.std(ddof=0), 4))

--- India ---
gdp_growth len= 29 nunique= 29 std= 0.0695
household_income len= 29 nunique= 29 std= 0.0662
unemployment_rate len= 29 nunique= 28 std= 0.0403
poverty_rate len= 29 nunique= 29 std= 0.0352
inflation len= 29 nunique= 29 std= 0.3623
imports len= 29 nunique= 29 std= 0.1763
exports len= 29 nunique= 29 std= 0.1407

--- Brazil ---
gdp_growth len= 29 nunique= 29 std= 0.1679
household_income len= 29 nunique= 29 std= 0.1742
unemployment_rate len= 29 nunique= 29 std= 0.1203
poverty_rate len= 29 nunique= 24 std= 0.0473
inflation len= 29 nunique= 29 std= 0.7919
imports len= 29 nunique= 29 std= 0.194
exports len= 29 nunique= 29 std= 0.1358

--- Vietnam ---
gdp_growth len= 29 nunique= 29 std= 0.0632
household_income len= 29 nunique= 29 std= 0.071
unemployment_rate len= 29 nunique= 29 std= 0.2005
poverty_rate len= 29 nunique= 29 std= 0.0505
inflation len= 26 nunique= 26 std= 0.6902
imports len= 29 nunique= 29 std= 0.1202
exports len= 29 nunique= 29 std= 0.0938

--- Canada ---
gdp_growth len= 29 nunique= 29 std= 0.079
household_income len= 29 nunique= 29 std= 0.0594
unemployment_rate len= 29 nunique= 29 std= 0.1473
poverty_rate len= 29 nunique= 8 std= 0.103
inflation len= 29 nunique= 29 std= 0.9407
imports len= 29 nunique= 29 std= 0.0956
exports len= 29 nunique= 29 std= 0.1215

--- South Africa ---
gdp_growth len= 29 nunique= 29 std= 0.127
household_income len= 29 nunique= 29 std= 0.1342
unemployment_rate len= 29 nunique= 29 std= 0.0955
poverty_rate len= 29 nunique= 26 std= 0.027
inflation len= 27 nunique= 27 std= 0.3183
imports len= 29 nunique= 29 std= 0.1625
exports len= 29 nunique= 29 std= 0.1321

--- Mexico ---
gdp_growth len= 29 nunique= 29 std= 0.1226
household_income len= 29 nunique= 29 std= 0.1311
unemployment_rate len= 29 nunique= 29 std= 0.145
poverty_rate len= 29 nunique= 27 std= 0.0342
inflation len= 29 nunique= 29 std= 0.4192
imports len= 29 nunique= 29 std= 0.1214
exports len= 29 nunique= 29 std= 0.1066

--- Egypt ---
gdp_growth len= 29 nunique= 29 std= 0.124
household_income len= 29 nunique= 29 std= 0.1267
unemployment_rate len= 29 nunique= 29 std= 0.1005
poverty_rate len= 29 nunique= 25 std= 0.081
inflation len= 29 nunique= 29 std= 0.4972
imports len= 29 nunique= 29 std= 0.1723
exports len= 29 nunique= 29 std= 0.1801

--- Germany ---
gdp_growth len= 29 nunique= 29 std= 0.0786
household_income len= 29 nunique= 29 std= 0.0771
unemployment_rate len= 29 nunique= 29 std= 0.1002
poverty_rate len= 29 nunique= 5 std= 0.1306
inflation len= 29 nunique= 29 std= 0.7624
imports len= 29 nunique= 29 std= 0.1095
exports len= 29 nunique= 29 std= 0.1049

--- Czech Republic ---
gdp_growth len= 29 nunique= 29 std= 0.1031
household_income len= 29 nunique= 29 std= 0.1026
unemployment_rate len= 29 nunique= 29 std= 0.1821
poverty_rate len= 23 nunique= 7 std= nan
inflation len= 29 nunique= 29 std= 1.0828
imports len= 29 nunique= 29 std= 0.1302
exports len= 29 nunique= 29 std= 0.119

--- Colombia ---
gdp_growth len= 29 nunique= 29 std= 0.1275
household_income len= 29 nunique= 29 std= 0.1193
unemployment_rate len= 29 nunique= 29 std= 0.1399
poverty_rate len= 29 nunique= 27 std= 0.0596
inflation len= 29 nunique= 29 std= 0.3703
imports len= 29 nunique= 29 std= 0.16
exports len= 29 nunique= 29 std= 0.1732

c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

In [24]:
import numpy as np
import pandas as pd

s = transformed_data["Czech Republic"].get_column("poverty_rate").to_pandas()

print(s)
print("has_nan:", s.isna().any())
print("has_pos_inf:", np.isposinf(s).any())
print("has_neg_inf:", np.isneginf(s).any())
print("finite_count:", np.isfinite(s).sum())
print("non_finite_rows:")
print(s[~np.isfinite(s)])

0    -0.223144
1     0.000000
2    -0.287682
3     0.000000
4     0.000000
5    -0.405465
6     0.000000
7     0.000000
8     0.405465
9     0.000000
10    0.000000
11   -0.405465
12    0.000000
13    0.000000
14   -0.693147
15    0.000000
16    0.000000
17    0.000000
18    0.000000
19    0.000000
20    0.000000
21    0.000000
22        -inf
23         NaN
24         NaN
25         NaN
26         NaN
27         NaN
28         NaN
Name: poverty_rate, dtype: float64
has_nan: True
has_pos_inf: False
has_neg_inf: True
finite_count: 22
non_finite_rows:
22   -inf
23    NaN
24    NaN
25    NaN
26    NaN
27    NaN
28    NaN
Name: poverty_rate, dtype: float64

In [25]:
# transformed_data['Czech Republic']

#### Transformed DF Stationarity Check

In [26]:
variables = [
    "gdp_growth", "household_income", "unemployment_rate",
    "poverty_rate", "inflation", "imports", "exports",
]

trans_df_stationarity_res = stationarity_check(variables=variables, data_dict=transformed_data).to_pandas()
trans_df_stationarity_res.to_csv(r"..\data\ecoms_results\transformed_data_stationarity_check.csv", index=False)

C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_17316\3161929974.py:81: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")

## ARDL Check
Goal:
1. ADF & KPSS for stationarity ``Done``
2. ARDL to harmonise stationary and non stationary data  ``Current``
3. Heteroskedasticity (Post-estimation Diagnostic)
4. Multicollinearity (Structural Consideration)

The focus is on ADRL right now.

Observations:
- ic: 'bic' was used in order to ensure model was not overfitting.
- review the effect of unemployment rate on the model.
- Review bounds test effect on the model.
   + We need to know:

        + Cointegration (Bounds Test)
        + F > Upper bound → Cointegration
        + F < Lower bound → No cointegration
        + Between → Inconclusive

**27-04-2026**
- Performed ADRL tests and reviewed with Temzy. 
- ADRL model summary reports to be shared for review. 

**06-05-2026**
- Created and parsed the model summaries into word document for review and possible adjustment.

**Date Modified 06-05-2026**

##### Functions

In [35]:
import pandas as pd
import numpy as np
import polars as pl
from statsmodels.tsa.ardl import ardl_select_order
from statsmodels.tsa.ardl import UECM


def adrl_data_selection(data_dict: dict):
    ardl_raw_data = {}
    ardl_log_data = {}

    for country, df in data_dict.items():
        df = df.sort("year")

        # Raw-level ARDL dataset
        ardl_raw_data[country] = df.select([
            "year",
            "gdp_growth",
            "household_income",
            "unemployment_rate",
            "poverty_rate",
            "inflation",
            "imports",
            "exports"
        ]).drop_nulls()

        # Logged-level ARDL dataset
        df_log = (
            df
            .with_columns([
                pl.col("gdp_growth").cast(pl.Float64).log().alias("log_gdp"),
                pl.col("household_income").cast(pl.Float64).log().alias("log_income"),
                pl.col("imports").cast(pl.Float64).log().alias("log_imports"),
                pl.col("exports").cast(pl.Float64).log().alias("log_exports"),
                (pl.col("imports") + pl.col("exports")).cast(pl.Float64).log().alias("log_trade"),
            ])
            .select([
                "year",
                "log_gdp",
                "log_income",
                "unemployment_rate",
                "poverty_rate",
                "inflation",
                "log_imports",
                "log_exports",
                "log_trade"
            ])
            .drop_nulls()
        )

        ardl_log_data[country] = df_log

    return ardl_raw_data, ardl_log_data


def run_ardl_models(data_dict: dict, y_col, x_cols, maxlag=2, maxorder=2, ic="bic"):
    selected_models = {}
    fitted_models = {}
    model_summaries = {}

    for country, data in data_dict.items():
        pdf = data.to_pandas().dropna()

        y = pdf[y_col]
        X = pdf[x_cols]

        sel = ardl_select_order(
            endog=y,
            maxlag=maxlag,
            exog=X,
            maxorder=maxorder,
            ic=ic,
            trend="c"
        )

        model = sel.model.fit()

        selected_models[country] = sel
        fitted_models[country] = model
        model_summaries[country] = model.summary()

        # print(f"\n--- {country} ---")
        # print("Selected ARDL order:", sel.model.ardl_order)
        # print(model.summary())

    return selected_models, fitted_models, model_summaries


def raw_df_adrl(data_dict: dict):
    raw_y = "gdp_growth"

    raw_predictors = [
        "household_income",
        "unemployment_rate",
        "poverty_rate",
        "inflation",
        "imports",
        "exports"
    ]

    raw_selected, raw_models, raw_model_summaries = run_ardl_models(
        data_dict=data_dict,
        y_col=raw_y,
        x_cols=raw_predictors,
        maxlag=2,
        maxorder=2,
        ic="bic"
    )
    return raw_selected, raw_models, raw_model_summaries


def logged_df_adrl_opt_a(data_dict: dict):
    log_y = "log_gdp"

    log_predictors_full = [
        "log_income",
        "unemployment_rate",
        "poverty_rate",
        "inflation",
        "log_imports",
        "log_exports"
    ]

    log_selected_full, log_models_full, opt_a_model_summaries = run_ardl_models(
        data_dict=data_dict,
        y_col=log_y,
        x_cols=log_predictors_full,
        maxlag=2,
        maxorder=2,
        ic="bic"
    )
    return log_selected_full, log_models_full, opt_a_model_summaries


def logged_df_adrl_opt_b(data_dict: dict):
    log_y = "log_gdp"

    log_predictors_clean = [
        "log_income",
        "unemployment_rate",
        "poverty_rate",
        "inflation",
        "log_trade"
    ]

    log_selected_clean, log_models_clean, opt_b_model_summaries = run_ardl_models(
        data_dict=data_dict,
        y_col="log_gdp",
        x_cols=log_predictors_clean,
        maxlag=2,
        maxorder=2,
        ic="bic"
    )
    return log_selected_clean, log_models_clean, opt_b_model_summaries


def run_bounds_tests(selected_models, case=3):
    bounds_results = {}
    uecm_models = {}

    for country, sel in selected_models.items():
        try:
            uecm_model = UECM.from_ardl(sel.model)
            uecm_res = uecm_model.fit()

            bt = uecm_res.bounds_test(case=case)

            uecm_models[country] = uecm_res
            bounds_results[country] = bt

            print(f"\n--- {country} Bounds Test ---")
            print(bt)

        except Exception as e:
            bounds_results[country] = str(e)
            print(f"\n--- {country} Bounds Test Failed ---")
            print(e)

    return bounds_results, uecm_models

##### ADRL Runs

In [36]:
raw_df, logged_df = adrl_data_selection(data_dict = country_data)

## Raw df ADRL
raw_df_selected, raw_df_models, raw_model_summaries = raw_df_adrl(raw_df)

In [37]:
## Logged data option A ADRL
log_df_opt_a_selected, log_df_opt_a_models, opt_a_model_summaries = logged_df_adrl_opt_a(logged_df)

In [38]:
## Logged data option B ADRL
log_df_opt_b_selected, log_df_opt_b_models, opt_b_model_summaries = logged_df_adrl_opt_b(logged_df)

### Parsing Model Summaries to Word Document

In [43]:
from docx import Document
from docx.shared import Pt

def convert_summary_to_word_document(model_summary_dict: dict, document_name: str):

    doc = Document()
    for country, summary_obj in model_summary_dict.items():
        summary_string = summary_obj.as_text() 
        lines = summary_string.split('\n')
        
        doc.add_heading(f'Model Report: {country}', level=1)
        p = doc.add_paragraph()
        run = p.add_run(summary_string)
        
        run.font.name = 'Times New Roman'
        run.font.size = Pt(8)
        doc.add_page_break()

    doc.save(f"../data/temzy/{document_name}.docx")

In [44]:
convert_summary_to_word_document(raw_model_summaries, document_name="raw_model_adrl_report")
convert_summary_to_word_document(opt_a_model_summaries, document_name="log_option_a_adrl_report")
convert_summary_to_word_document(opt_b_model_summaries, document_name="log_option_b_adrl_report")

##### Bounds test using UECM

In [60]:
## raw df adrl selected model bounds test. 

run_bounds_tests(raw_df_selected)

--- Mexico Bounds Test ---
BoundsTestResult
Stat: 1.72789
Upper P-value: 0.643
Lower P-value: 0.343
Null: No Cointegration
Alternative: Possible Cointegration


--- India Bounds Test ---
BoundsTestResult
Stat: 21.77472
Upper P-value: 0
Lower P-value: 0
Null: No Cointegration
Alternative: Possible Cointegration


--- Colombia Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Canada Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Egypt Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- South Africa Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Germany Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Vietnam Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Brazil Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Czech Republic Bounds Test Failed ---
All included exog variables must have a lag length >= 1

c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: imports, inflation, poverty_rate, unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: imports, inflation, poverty_rate, unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: inflation.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: inflation.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: imports, poverty_rate, unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: exports, inflation, poverty_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: exports, inflation.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: inflation.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: inflation.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: imports.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: exports, poverty_rate, unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)

({'Mexico': BoundsTestResult
  Stat: 1.72789
  Upper P-value: 0.643
  Lower P-value: 0.343
  Null: No Cointegration
  Alternative: Possible Cointegration,
  'India': BoundsTestResult
  Stat: 21.77472
  Upper P-value: 0
  Lower P-value: 0
  Null: No Cointegration
  Alternative: Possible Cointegration,
  'Colombia': 'All included exog variables must have a lag length >= 1',
  'Canada': 'All included exog variables must have a lag length >= 1',
  'Egypt': 'All included exog variables must have a lag length >= 1',
  'South Africa': 'All included exog variables must have a lag length >= 1',
  'Germany': 'All included exog variables must have a lag length >= 1',
  'Vietnam': 'All included exog variables must have a lag length >= 1',
  'Brazil': 'All included exog variables must have a lag length >= 1',
  'Czech Republic': 'All included exog variables must have a lag length >= 1'},
 {'Mexico': <statsmodels.tsa.ardl.model.UECMResultsWrapper at 0x230d44c5b20>,
  'India': <statsmodels.tsa.ardl.model.UECMResultsWrapper at 0x230d5806df0>})

In [68]:
run_bounds_tests(log_df_opt_a_selected)

c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: log_imports, unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: log_exports, log_imports.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: log_imports, unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: inflation, log_imports.
  return _format_order(self.data.orig_exog, order, self._causal)

--- Mexico Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- India Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Colombia Bounds Test Failed ---
All included exog variables must have a lag length >= 1

c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: inflation, log_imports.
  return _format_order(self.data.orig_exog, order, self._causal)

--- Canada Bounds Test ---
BoundsTestResult
Stat: 3.34637
Upper P-value: 0.101
Lower P-value: 0.0117
Null: No Cointegration
Alternative: Possible Cointegration


--- Egypt Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- South Africa Bounds Test ---
BoundsTestResult
Stat: 8.42556
Upper P-value: 1.8e-07
Lower P-value: 8.8e-10
Null: No Cointegration
Alternative: Possible Cointegration


--- Germany Bounds Test ---
BoundsTestResult
Stat: 10.42648
Upper P-value: 6.61e-10
Lower P-value: 2.43e-12
Null: No Cointegration
Alternative: Possible Cointegration


--- Vietnam Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Brazil Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Czech Republic Bounds Test Failed ---
All included exog variables must have a lag length >= 1

c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: log_exports, unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: unemployment_rate, inflation, log_imports.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: unemployment_rate, inflation, poverty_rate, log_imports.
  return _format_order(self.data.orig_exog, order, self._causal)

({'Mexico': 'All included exog variables must have a lag length >= 1',
  'India': 'All included exog variables must have a lag length >= 1',
  'Colombia': 'All included exog variables must have a lag length >= 1',
  'Canada': BoundsTestResult
  Stat: 3.34637
  Upper P-value: 0.101
  Lower P-value: 0.0117
  Null: No Cointegration
  Alternative: Possible Cointegration,
  'Egypt': 'All included exog variables must have a lag length >= 1',
  'South Africa': BoundsTestResult
  Stat: 8.42556
  Upper P-value: 1.8e-07
  Lower P-value: 8.8e-10
  Null: No Cointegration
  Alternative: Possible Cointegration,
  'Germany': BoundsTestResult
  Stat: 10.42648
  Upper P-value: 6.61e-10
  Lower P-value: 2.43e-12
  Null: No Cointegration
  Alternative: Possible Cointegration,
  'Vietnam': 'All included exog variables must have a lag length >= 1',
  'Brazil': 'All included exog variables must have a lag length >= 1',
  'Czech Republic': 'All included exog variables must have a lag length >= 1'},
 {'Canada': <statsmodels.tsa.ardl.model.UECMResultsWrapper at 0x230d74c2cf0>,
  'South Africa': <statsmodels.tsa.ardl.model.UECMResultsWrapper at 0x230d74a5670>,
  'Germany': <statsmodels.tsa.ardl.model.UECMResultsWrapper at 0x230d74a4ef0>})

In [69]:
run_bounds_tests(log_df_opt_b_selected)

c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: log_trade.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: inflation.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: inflation.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: log_trade, inflation, poverty_rate.
  return _format_order(self.data.orig_exog, order, self._causal)

--- Mexico Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- India Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Colombia Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Canada Bounds Test ---
BoundsTestResult
Stat: 3.25348
Upper P-value: 0.116
Lower P-value: 0.0142
Null: No Cointegration
Alternative: Possible Cointegration


--- Egypt Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- South Africa Bounds Test ---
BoundsTestResult
Stat: 10.73038
Upper P-value: 4.58e-06
Lower P-value: 3.9e-07
Null: No Cointegration
Alternative: Possible Cointegration


--- Germany Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Vietnam Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Brazil Bounds Test Failed ---
All included exog variables must have a lag length >= 1

--- Czech Republic Bounds Test Failed ---
All included exog variables must have a lag length >= 1

c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: log_trade, inflation, poverty_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)
c:\Users\APIN PC\OneDrive\Documents\DS\research_projects\.venv\Lib\site-packages\statsmodels\tsa\ardl\model.py:455: SpecificationWarning: exog contains variables that are missing from the order dictionary.  Missing keys: inflation, poverty_rate, unemployment_rate.
  return _format_order(self.data.orig_exog, order, self._causal)

({'Mexico': 'All included exog variables must have a lag length >= 1',
  'India': 'All included exog variables must have a lag length >= 1',
  'Colombia': 'All included exog variables must have a lag length >= 1',
  'Canada': BoundsTestResult
  Stat: 3.25348
  Upper P-value: 0.116
  Lower P-value: 0.0142
  Null: No Cointegration
  Alternative: Possible Cointegration,
  'Egypt': 'All included exog variables must have a lag length >= 1',
  'South Africa': BoundsTestResult
  Stat: 10.73038
  Upper P-value: 4.58e-06
  Lower P-value: 3.9e-07
  Null: No Cointegration
  Alternative: Possible Cointegration,
  'Germany': 'All included exog variables must have a lag length >= 1',
  'Vietnam': 'All included exog variables must have a lag length >= 1',
  'Brazil': 'All included exog variables must have a lag length >= 1',
  'Czech Republic': 'All included exog variables must have a lag length >= 1'},
 {'Canada': <statsmodels.tsa.ardl.model.UECMResultsWrapper at 0x230d74c0d10>,
  'South Africa': <statsmodels.tsa.ardl.model.UECMResultsWrapper at 0x230e0714650>})

### Standardization

In [58]:
standardized_data = {}

predictors = [
    "income_growth",
    "imports_growth",
    "exports_growth",
    "unemployment_rate",
    "inflation"
]

for country, df in transformed_data.items():
    
    df_std = df.with_columns([
        ((pl.col(col) - pl.col(col).mean()) / pl.col(col).std()).alias(col)
        for col in predictors
    ])
    
    standardized_data[country] = df_std

In [60]:
stan_df_stationarity_res = stationarity_check(variables=variables, data_dict=standardized_data).to_pandas()
stan_df_stationarity_res.to_csv('stan_check.csv')

C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  result = kpss(series, regression="c", nlags="auto")
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_20400\2388354754.py:15: InterpolationWarning: The test statistic is outside of the range of p-values available in the

## Multicollinearity

### Functions

In [82]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calculate_vif(df, predictors):
    pdf = df.select(predictors).to_pandas().dropna()
    
    vif_data = []
    
    for i in range(len(pdf.columns)):
        vif = variance_inflation_factor(pdf.values, i)
        vif_data.append({
            "variable": pdf.columns[i],
            "VIF": vif
        })
    
    return pd.DataFrame(vif_data)

def condition_index_from_polars(data: pl.DataFrame, predictors: list[str]):
    pdf = data.select(predictors).to_pandas().dropna()

    Z = (pdf - pdf.mean()) / pdf.std(ddof=0)
    Z = Z.loc[:, Z.std(ddof=0) > 0]
    X = Z.values

    eigvals = np.linalg.eigvals(X.T @ X)
    eigvals = np.real(eigvals)
    cond_idx = np.sqrt(eigvals.max() / eigvals)

    result = pl.DataFrame({
        "dimension": list(range(1, len(cond_idx) + 1)),
        "condition_index": cond_idx
    })

    return result

### VIF

In [70]:
trans_predictors = ["income_growth", "imports_growth", "exports_growth", "unemployment_rate",
    "inflation"
]
# predictors = [ "household_income", "unemployment_rate",
#     "poverty_rate", "inflation", "imports", "exports",
#     'income_growth', 'imports_growth', 'exports_growth'
# ]
vif_res = {}

for country, df in standardized_data.items():
    vif_df = calculate_vif(df, predictors=trans_predictors)
    print(f"\n--- {country} ---")
    print(vif_df)
    vif_res[country] = vif_df

--- Czech Republic ---
            variable        VIF
0      income_growth   3.697418
1     imports_growth  17.086304
2     exports_growth  15.553625
3  unemployment_rate   1.678677
4          inflation   1.252585

--- Canada ---
            variable        VIF
0      income_growth   1.665802
1     imports_growth  13.673060
2     exports_growth  13.068888
3  unemployment_rate   1.484729
4          inflation   1.936349

--- Mexico ---
            variable        VIF
0      income_growth   6.019204
1     imports_growth  11.988152
2     exports_growth   6.521261
3  unemployment_rate   1.698515
4          inflation   1.507822

--- Vietnam ---
            variable       VIF
0      income_growth  3.462431
1     imports_growth  3.876146
2     exports_growth  3.314428
3  unemployment_rate  1.046966
4          inflation  2.482538

--- Colombia ---
            variable       VIF
0      income_growth  4.521326
1     imports_growth  3.904360
2     exports_growth  3.734630
3  unemployment_rate  1.839095
4          inflation  1.711587

--- Egypt ---
            variable       VIF
0      income_growth  1.564301
1     imports_growth  2.089142
2     exports_growth  1.482835
3  unemployment_rate  1.208599
4          inflation  1.323351

--- India ---
            variable        VIF
0      income_growth   3.676073
1     imports_growth  11.762679
2     exports_growth   9.751568
3  unemployment_rate   1.168140
4          inflation   1.036382

--- Brazil ---
            variable       VIF
0      income_growth  2.674210
1     imports_growth  5.585380
2     exports_growth  4.539518
3  unemployment_rate  1.679080
4          inflation  1.135726

--- Germany ---
            variable        VIF
0      income_growth   2.714695
1     imports_growth  17.845751
2     exports_growth  17.818222
3  unemployment_rate   1.281445
4          inflation   1.399529

--- South Africa ---
            variable       VIF
0      income_growth  2.344399
1     imports_growth  4.137590
2     exports_growth  3.986491
3  unemployment_rate  1.061133
4          inflation  1.254027

In [78]:
final_trans_df = {}

for country, data in standardized_data.items():
    df = (
        data.with_columns([
    ((pl.col("imports_growth") + pl.col("exports_growth")) / 2)
    .alias("trade_growth")
])
)

    final_trans_df[country] = df

In [ ]:
trans_predictors = ["income_growth",  "unemployment_rate",
    "inflation", 'trade_growth',
]
# predictors = [ "household_income", "unemployment_rate",
#     "poverty_rate", "inflation", "imports", "exports",
#     'income_growth', 'imports_growth', 'exports_growth'
# ]
vif_res = {}

for country, df in final_trans_df.items():
    vif_df = calculate_vif(df, predictors=trans_predictors)
    print(f"\n--- {country} ---")
    print(vif_df)
    vif_res[country] = vif_df

In [103]:
vi_result_df = pl.DataFrame(vif_res)
vi_result_df.to_pandas().to_csv(r'..\data\ecoms_results\vi_results.csv')

### Condition Index

In [101]:
results = []

for country, df in final_trans_df.items():
    ci_df = condition_index_from_polars(df, predictors)
    max_ci = ci_df["condition_index"].max()
    
    results.append({
        "country": country,
        "max_condition_index": max_ci
    })

ci_results = pl.DataFrame(results)
ci_res = ci_results.to_pandas()
ci_res.to_csv(r'..\data\ecoms_results\ci_results.csv')

## Heteroskedasticity

### Functions

In [ ]:
import statsmodels.api as sm
from statsmodels.stats.diagnostic import het_breuschpagan, het_white


def breusch_pagan_test(df, predictors):
    pdf = df.select(["gdp_growth"] + predictors).to_pandas().dropna()
    
    y = pdf["gdp_growth"]
    X = pdf[predictors]
    X = sm.add_constant(X)
    
    model = sm.OLS(y, X).fit()
    
    bp_test = het_breuschpagan(model.resid, model.model.exog)
    
    return {
        "LM_stat": bp_test[0],
        "LM_pvalue": bp_test[1],
        "F_stat": bp_test[2],
        "F_pvalue": bp_test[3]
    }


def white_test(df, predictors):
    pdf = df.select(["gdp_growth"] + predictors).to_pandas().dropna()
    
    y = pdf["gdp_growth"]
    X = pdf[predictors]
    X = sm.add_constant(X)
    
    model = sm.OLS(y, X).fit()
    
    white = het_white(model.resid, model.model.exog)
    
    return {
        "LM_stat": white[0],
        "LM_pvalue": white[1],
        "F_stat": white[2],
        "F_pvalue": white[3]
    }

In [91]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.stats.diagnostic import het_breuschpagan, het_white

predictors = ["income_growth", "trade_growth", "unemployment_rate", "inflation"]

models = {}
hetero_results = []

for country, data in final_trans_df.items():
    pdf = data.to_pandas().dropna()

    y = pdf["gdp_growth"]
    X = pdf[predictors]
    X = sm.add_constant(X)

    # Fit OLS model
    model = sm.OLS(y, X).fit()
    models[country] = model

    # Breusch-Pagan test
    bp_test = het_breuschpagan(model.resid, model.model.exog)

    # White test
    white_test = het_white(model.resid, model.model.exog)

    # Store results
    hetero_results.append({
        "country": country,
        "bp_lm_stat": bp_test[0],
        "bp_lm_pvalue": bp_test[1],
        "bp_f_stat": bp_test[2],
        "bp_f_pvalue": bp_test[3],
        "white_lm_stat": white_test[0],
        "white_lm_pvalue": white_test[1],
        "white_f_stat": white_test[2],
        "white_f_pvalue": white_test[3]
    })

    # Print model summary
    print(f"\n--- {country} : OLS Regression Summary ---")
    print(model.summary())

    # Print heteroskedasticity test summaries
    print(f"\n--- {country} : Breusch-Pagan Test ---")
    print({
        "LM_stat": bp_test[0],
        "LM_pvalue": bp_test[1],
        "F_stat": bp_test[2],
        "F_pvalue": bp_test[3]
    })

    print(f"\n--- {country} : White Test ---")
    print({
        "LM_stat": white_test[0],
        "LM_pvalue": white_test[1],
        "F_stat": white_test[2],
        "F_pvalue": white_test[3]
    })

--- Czech Republic : OLS Regression Summary ---
                            OLS Regression Results
==============================================================================
Dep. Variable:             gdp_growth   R-squared:                       0.966
Model:                            OLS   Adj. R-squared:                  0.961
Method:                 Least Squares   F-statistic:                     171.6
Date:                Sat, 11 Apr 2026   Prob (F-statistic):           2.79e-17
Time:                        12:16:14   Log-Likelihood:                 73.853
No. Observations:                  29   AIC:                            -137.7
Df Residuals:                      24   BIC:                            -130.9
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0680      0.004     17.567      0.000       0.060       0.076
income_growth         0.0876      0.007     11.706      0.000       0.072       0.103
trade_growth          0.0205      0.008      2.694      0.013       0.005       0.036
unemployment_rate     0.0007      0.005      0.140      0.890      -0.009       0.010
inflation            -0.0074      0.004     -1.684      0.105      -0.017       0.002
==============================================================================
Omnibus:                        0.254   Durbin-Watson:                   2.556
Prob(Omnibus):                  0.881   Jarque-Bera (JB):                0.425
Skew:                           0.165   Prob(JB):                        0.808
Kurtosis:                       2.507   Cond. No.                         3.71
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

--- Czech Republic : Breusch-Pagan Test ---
{'LM_stat': np.float64(4.438617567304604), 'LM_pvalue': np.float64(0.34988802278054404), 'F_stat': np.float64(1.0842917932980953), 'F_pvalue': np.float64(0.3864260784593987)}

--- Czech Republic : White Test ---
{'LM_stat': np.float64(20.232621124737836), 'LM_pvalue': np.float64(0.12297634707733061), 'F_stat': np.float64(2.307716070287065), 'F_pvalue': np.float64(0.06480073051817772)}

--- Canada : OLS Regression Summary ---
                            OLS Regression Results
==============================================================================
Dep. Variable:             gdp_growth   R-squared:                       0.937
Model:                            OLS   Adj. R-squared:                  0.927
Method:                 Least Squares   F-statistic:                     89.96
Date:                Sat, 11 Apr 2026   Prob (F-statistic):           4.37e-14
Time:                        12:16:14   Log-Likelihood:                 72.643
No. Observations:                  29   AIC:                            -135.3
Df Residuals:                      24   BIC:                            -128.4
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0452      0.004     11.195      0.000       0.037       0.053
income_growth         0.0449      0.005      8.661      0.000       0.034       0.056
trade_growth          0.0434      0.006      7.593      0.000       0.032       0.055
unemployment_rate    -0.0030      0.005     -0.590      0.561      -0.013       0.007
inflation            -0.0021      0.006     -0.374      0.711      -0.014       0.010
==============================================================================
Omnibus:                        3.554   Durbin-Watson:                   2.532
Prob(Omnibus):                  0.169   Jarque-Bera (JB):                2.051
Skew:                          -0.448   Prob(JB):                        0.359
Kurtosis:                       3.946   Cond. No.                         2.77
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

--- Canada : Breusch-Pagan Test ---
{'LM_stat': np.float64(14.61253211274844), 'LM_pvalue': np.float64(0.005576154600504509), 'F_stat': np.float64(6.0938584442769), 'F_pvalue': np.float64(0.0015668012013903016)}

--- Canada : White Test ---
{'LM_stat': np.float64(22.954415008833067), 'LM_pvalue': np.float64(0.06101553142989398), 'F_stat': np.float64(3.7968889763970304), 'F_pvalue': np.float64(0.008879944118894203)}

--- Mexico : OLS Regression Summary ---
                            OLS Regression Results
==============================================================================
Dep. Variable:             gdp_growth   R-squared:                       0.960
Model:                            OLS   Adj. R-squared:                  0.953
Method:                 Least Squares   F-statistic:                     143.0
Date:                Sat, 11 Apr 2026   Prob (F-statistic):           2.28e-16
Time:                        12:16:14   Log-Likelihood:                 66.295
No. Observations:                  29   AIC:                            -122.6
Df Residuals:                      24   BIC:                            -115.8
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0359      0.005      7.151      0.000       0.026       0.046
income_growth         0.1023      0.008     12.680      0.000       0.086       0.119
trade_growth          0.0323      0.008      4.184      0.000       0.016       0.048
unemployment_rate    -0.0003      0.006     -0.048      0.962      -0.013       0.013
inflation            -0.0064      0.006     -1.060      0.300      -0.019       0.006
==============================================================================
Omnibus:                        0.104   Durbin-Watson:                   2.087
Prob(Omnibus):                  0.949   Jarque-Bera (JB):                0.325
Skew:                          -0.024   Prob(JB):                        0.850
Kurtosis:                       2.484   Cond. No.                         2.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

--- Mexico : Breusch-Pagan Test ---
{'LM_stat': np.float64(3.1321533015564924), 'LM_pvalue': np.float64(0.5359585176595518), 'F_stat': np.float64(0.72649726235117), 'F_pvalue': np.float64(0.5825473751999583)}

--- Mexico : White Test ---
{'LM_stat': np.float64(14.251368165854053), 'LM_pvalue': np.float64(0.4311568013156513), 'F_stat': np.float64(0.966284081541677), 'F_pvalue': np.float64(0.525128048758052)}

--- Vietnam : OLS Regression Summary ---
                            OLS Regression Results
==============================================================================
Dep. Variable:             gdp_growth   R-squared:                       0.830
Model:                            OLS   Adj. R-squared:                  0.802
Method:                 Least Squares   F-statistic:                     29.35
Date:                Sat, 11 Apr 2026   Prob (F-statistic):           6.28e-09
Time:                        12:16:14   Log-Likelihood:                 64.644
No. Observations:                  29   AIC:                            -119.3
Df Residuals:                      24   BIC:                            -112.5
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.1082      0.005     20.356      0.000       0.097       0.119
income_growth         0.0243      0.010      2.549      0.018       0.005       0.044
trade_growth          0.0258      0.008      3.346      0.003       0.010       0.042
unemployment_rate     0.0004      0.006      0.067      0.947      -0.011       0.012
inflation             0.0189      0.008      2.374      0.026       0.002       0.035
==============================================================================
Omnibus:                       18.841   Durbin-Watson:                   1.988
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               25.861
Skew:                           1.540   Prob(JB):                     2.42e-06
Kurtosis:                       6.452   Cond. No.                         3.29
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

--- Vietnam : Breusch-Pagan Test ---
{'LM_stat': np.float64(1.8856090516014783), 'LM_pvalue': np.float64(0.7567881156506444), 'F_stat': np.float64(0.41725644257102856), 'F_pvalue': np.float64(0.7945180285334519)}

--- Vietnam : White Test ---
{'LM_stat': np.float64(12.847643996107827), 'LM_pvalue': np.float64(0.5385539118330656), 'F_stat': np.float64(0.7954037165235819), 'F_pvalue': np.float64(0.6628378256088173)}

--- Colombia : OLS Regression Summary ---
                            OLS Regression Results
==============================================================================
Dep. Variable:             gdp_growth   R-squared:                       0.956
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     129.7
Date:                Sat, 11 Apr 2026   Prob (F-statistic):           6.94e-16
Time:                        12:16:14   Log-Likelihood:                 63.814
No. Observations:                  29   AIC:                            -117.6
Df Residuals:                      24   BIC:                            -110.8
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0534      0.005      9.763      0.000       0.042       0.065
income_growth         0.1111      0.012      9.385      0.000       0.087       0.135
trade_growth          0.0179      0.012      1.484      0.151      -0.007       0.043
unemployment_rate    -0.0005      0.007     -0.069      0.946      -0.016       0.015
inflation             0.0137      0.007      1.937      0.065      -0.001       0.028
==============================================================================
Omnibus:                        5.060   Durbin-Watson:                   1.698
Prob(Omnibus):                  0.080   Jarque-Bera (JB):                3.673
Skew:                          -0.853   Prob(JB):                        0.159
Kurtosis:                       3.362   Cond. No.                         4.14
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

--- Colombia : Breusch-Pagan Test ---
{'LM_stat': np.float64(1.921221808803908), 'LM_pvalue': np.float64(0.7502454991568634), 'F_stat': np.float64(0.4256961215691494), 'F_pvalue': np.float64(0.788559438002916)}

--- Colombia : White Test ---
{'LM_stat': np.float64(21.02728053727635), 'LM_pvalue': np.float64(0.10093544957477309), 'F_stat': np.float64(2.637403791214421), 'F_pvalue': np.float64(0.04008856926335259)}

--- Egypt : OLS Regression Summary ---
                            OLS Regression Results
==============================================================================
Dep. Variable:             gdp_growth   R-squared:                       0.930
Model:                            OLS   Adj. R-squared:                  0.918
Method:                 Least Squares   F-statistic:                     79.35
Date:                Sat, 11 Apr 2026   Prob (F-statistic):           1.77e-13
Time:                        12:16:14   Log-Likelihood:                 57.883
No. Observations:                  29   AIC:                            -105.8
Df Residuals:                      24   BIC:                            -98.93
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0729      0.007     10.856      0.000       0.059       0.087
income_growth         0.1169      0.007     15.913      0.000       0.102       0.132
trade_growth          0.0055      0.009      0.629      0.535      -0.013       0.023
unemployment_rate    -0.0094      0.007     -1.253      0.222      -0.025       0.006
inflation            -0.0057      0.008     -0.752      0.460      -0.021       0.010
==============================================================================
Omnibus:                        2.062   Durbin-Watson:                   1.776
Prob(Omnibus):                  0.357   Jarque-Bera (JB):                1.198
Skew:                          -0.137   Prob(JB):                        0.549
Kurtosis:                       2.043   Cond. No.                         1.83
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

--- Egypt : Breusch-Pagan Test ---
{'LM_stat': np.float64(3.147835369218517), 'LM_pvalue': np.float64(0.5333973926011599), 'F_stat': np.float64(0.7305775932133294), 'F_pvalue': np.float64(0.5799579873113856)}

--- Egypt : White Test ---
{'LM_stat': np.float64(13.084868478949037), 'LM_pvalue': np.float64(0.5198521317860298), 'F_stat': np.float64(0.8221652747036159), 'F_pvalue': np.float64(0.640417290970496)}

--- India : OLS Regression Summary ---
                            OLS Regression Results
==============================================================================
Dep. Variable:             gdp_growth   R-squared:                       0.878
Model:                            OLS   Adj. R-squared:                  0.858
Method:                 Least Squares   F-statistic:                     43.16
Date:                Sat, 11 Apr 2026   Prob (F-statistic):           1.26e-10
Time:                        12:16:15   Log-Likelihood:                 66.682
No. Observations:                  29   AIC:                            -123.4
Df Residuals:                      24   BIC:                            -116.5
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0852      0.005     17.202      0.000       0.075       0.095
income_growth         0.0684      0.010      7.195      0.000       0.049       0.088
trade_growth         -0.0018      0.009     -0.197      0.845      -0.021       0.017
unemployment_rate     0.0026      0.005      0.477      0.638      -0.009       0.014
inflation            -0.0018      0.005     -0.344      0.733      -0.012       0.009
==============================================================================
Omnibus:                        1.972   Durbin-Watson:                   2.297
Prob(Omnibus):                  0.373   Jarque-Bera (JB):                1.646
Skew:                          -0.564   Prob(JB):                        0.439
Kurtosis:                       2.699   Cond. No.                         3.53
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

--- India : Breusch-Pagan Test ---
{'LM_stat': np.float64(5.736413641355131), 'LM_pvalue': np.float64(0.2197168131295705), 'F_stat': np.float64(1.4795002506284116), 'F_pvalue': np.float64(0.2395791391607822)}

--- India : White Test ---
{'LM_stat': np.float64(15.454693403755876), 'LM_pvalue': np.float64(0.34779548433442437), 'F_stat': np.float64(1.1409629818228841), 'F_pvalue': np.float64(0.4042885003707101)}

--- Brazil : OLS Regression Summary ---
                            OLS Regression Results
==============================================================================
Dep. Variable:             gdp_growth   R-squared:                       0.958
Model:                            OLS   Adj. R-squared:                  0.951
Method:                 Least Squares   F-statistic:                     137.0
Date:                Sat, 11 Apr 2026   Prob (F-statistic):           3.72e-16
Time:                        12:16:15   Log-Likelihood:                 56.570
No. Observations:                  29   AIC:                            -103.1
Df Residuals:                      24   BIC:                            -96.30
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0472      0.007      6.727      0.000       0.033       0.062
income_growth         0.1414      0.012     12.252      0.000       0.118       0.165
trade_growth          0.0350      0.011      3.070      0.005       0.011       0.058
unemployment_rate     0.0029      0.008      0.344      0.734      -0.014       0.020
inflation             0.0042      0.008      0.550      0.588      -0.012       0.020
==============================================================================
Omnibus:                       15.604   Durbin-Watson:                   2.612
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               18.975
Skew:                          -1.322   Prob(JB):                     7.58e-05
Kurtosis:                       5.951   Cond. No.                         3.01
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

--- Brazil : Breusch-Pagan Test ---
{'LM_stat': np.float64(3.443285042896905), 'LM_pvalue': np.float64(0.4865542098911879), 'F_stat': np.float64(0.8083867700547083), 'F_pvalue': np.float64(0.5320612866340149)}

--- Brazil : White Test ---
{'LM_stat': np.float64(27.09337570085112), 'LM_pvalue': np.float64(0.018722401554021762), 'F_stat': np.float64(14.210128189882843), 'F_pvalue': np.float64(6.391311313170557e-06)}

--- Germany : OLS Regression Summary ---
                            OLS Regression Results

In [ ]:
hetero_df = pd.DataFrame(hetero_results)
hetero_df["bp_decision"] = hetero_df["bp_lm_pvalue"].apply(
    lambda p: "Heteroskedasticity present" if p < 0.05 else "No heteroskedasticity"
)

hetero_df["white_decision"] = hetero_df["white_lm_pvalue"].apply(
    lambda p: "Heteroskedasticity present" if p < 0.05 else "No heteroskedasticity"
)

hetero_df
for col in hetero_df.columns:
    if hetero_df[col].dtype == float:
        hetero_df[col] = round(hetero_df[col], 3)

hetero_df.to_csv(r'..\data\ecoms_results\heteroskedasticity_results.csv')

In [109]:
import polars as pl
import polars.selectors as cs

final_combined_df = pl.concat([
    df.with_columns(pl.lit(country).alias("country"))
    for country, df in final_trans_df.items()
])

final_combined_df = final_combined_df.with_columns(
    cs.float().round(2)
)

final_combined_df.to_pandas().to_csv(r"..\data\ecoms_results\final_dataframe.csv")

# OLS Model Fitting

In [ ]:
predictors = ["household_income", "unemployment_rate", "poverty_rate", "inflation", "imports", "exports"]

models = {}

for country, data in transformed_country_data.items():
    pdf = data.to_pandas()

    y = pdf["gdp_growth_log"]
    X = pdf[predictors]
    X = sm.add_constant(X)

    model = sm.OLS(y, X).fit()
    models[country] = model

    print(f"\n--- {country} ---")
    print(model.summary())

--- Mexico ---
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.922
Model:                            OLS   Adj. R-squared:                  0.900
Method:                 Least Squares   F-statistic:                     43.20
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           4.52e-11
Time:                        14:57:21   Log-Likelihood:                 56.667
No. Observations:                  29   AIC:                            -99.33
Df Residuals:                      22   BIC:                            -89.76
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0288      0.020      1.474      0.155      -0.012       0.069
household_income   7.125e-05   7.24e-06      9.840      0.000    5.62e-05    8.63e-05
unemployment_rate    -0.0493      0.020     -2.455      0.022      -0.091      -0.008
poverty_rate         -0.0021      0.056     -0.038      0.970      -0.118       0.114
inflation            -0.0015      0.001     -1.217      0.236      -0.004       0.001
imports           -8.483e-07   7.86e-07     -1.080      0.292   -2.48e-06    7.81e-07
exports             1.07e-07   9.08e-07      0.118      0.907   -1.78e-06    1.99e-06
==============================================================================
Omnibus:                        1.473   Durbin-Watson:                   1.764
Prob(Omnibus):                  0.479   Jarque-Bera (JB):                1.300
Skew:                           0.372   Prob(JB):                        0.522
Kurtosis:                       2.277   Cond. No.                     4.44e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

--- Egypt ---
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.867
Model:                            OLS   Adj. R-squared:                  0.831
Method:                 Least Squares   F-statistic:                     23.96
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.35e-08
Time:                        14:57:21   Log-Likelihood:                 48.670
No. Observations:                  29   AIC:                            -83.34
Df Residuals:                      22   BIC:                            -73.77
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0430      0.021      2.031      0.054      -0.001       0.087
household_income      0.0001   1.48e-05      7.849      0.000    8.54e-05       0.000
unemployment_rate    -0.0064      0.011     -0.585      0.564      -0.029       0.016
poverty_rate         -0.1536      0.061     -2.515      0.020      -0.280      -0.027
inflation            -0.0020      0.002     -0.995      0.330      -0.006       0.002
imports            2.697e-06   2.26e-06      1.191      0.246      -2e-06    7.39e-06
exports           -1.156e-06   3.87e-06     -0.299      0.768   -9.17e-06    6.86e-06
==============================================================================
Omnibus:                        0.059   Durbin-Watson:                   1.796
Prob(Omnibus):                  0.971   Jarque-Bera (JB):                0.275
Skew:                          -0.015   Prob(JB):                        0.872
Kurtosis:                       2.524   Cond. No.                     5.11e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.11e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

--- Czech Republic ---
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.708
Model:                            OLS   Adj. R-squared:                  0.629
Method:                 Least Squares   F-statistic:                     8.910
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           5.42e-05
Time:                        14:57:21   Log-Likelihood:                 42.607
No. Observations:                  29   AIC:                            -71.21
Df Residuals:                      22   BIC:                            -61.64
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0090      0.021      0.439      0.665      -0.034       0.052
household_income   4.531e-05   1.27e-05      3.572      0.002     1.9e-05    7.16e-05
unemployment_rate    -0.0115      0.014     -0.830      0.416      -0.040       0.017
poverty_rate          0.0468      0.269      0.174      0.863      -0.511       0.605
inflation             0.0030      0.004      0.769      0.450      -0.005       0.011
imports           -5.469e-06   5.46e-06     -1.002      0.327   -1.68e-05    5.85e-06
exports            5.999e-06   6.09e-06      0.985      0.335   -6.63e-06    1.86e-05
==============================================================================
Omnibus:                        1.521   Durbin-Watson:                   0.970
Prob(Omnibus):                  0.468   Jarque-Bera (JB):                1.413
Skew:                           0.467   Prob(JB):                        0.493
Kurtosis:                       2.453   Cond. No.                     4.65e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

--- Canada ---
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.919
Model:                            OLS   Adj. R-squared:                  0.897
Method:                 Least Squares   F-statistic:                     41.71
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           6.41e-11
Time:                        14:57:21   Log-Likelihood:                 68.925
No. Observations:                  29   AIC:                            -123.9
Df Residuals:                      22   BIC:                            -114.3
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0065      0.006      1.012      0.323      -0.007       0.020
household_income   1.962e-05   4.44e-06      4.417      0.000    1.04e-05    2.88e-05
unemployment_rate    -0.0159      0.011     -1.398      0.176      -0.039       0.008
poverty_rate         -0.2766      0.136     -2.040      0.054      -0.558       0.005
inflation            -0.0074      0.007     -1.136      0.268      -0.021       0.006
imports           -6.077e-07   7.33e-07     -0.829      0.416   -2.13e-06    9.13e-07
exports            1.055e-06   5.06e-07      2.086      0.049     6.1e-09     2.1e-06
==============================================================================
Omnibus:                        0.112   Durbin-Watson:                   1.626
Prob(Omnibus):                  0.946   Jarque-Bera (JB):                0.294
Skew:                          -0.111   Prob(JB):                        0.863
Kurtosis:                       2.560   Cond. No.                     1.79e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.79e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

--- South Africa ---
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.934
Model:                            OLS   Adj. R-squared:                  0.916
Method:                 Least Squares   F-statistic:                     51.85
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           7.17e-12
Time:                        14:57:21   Log-Likelihood:                 58.088
No. Observations:                  29   AIC:                            -102.2
Df Residuals:                      22   BIC:                            -92.60
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0208      0.011      1.897      0.071      -0.002       0.044
household_income      0.0001   1.71e-05      8.365      0.000       0.000       0.000
unemployment_rate    -0.0020      0.003     -0.603      0.553      -0.009       0.005
poverty_rate         -0.0192      0.013     -1.448      0.162      -0.047       0.008
inflation            -0.0048      0.004     -1.175      0.252      -0.013       0.004
imports            2.453e-07   1.25e-06      0.196      0.846   -2.35e-06    2.84e-06
exports            6.875e-07   1.43e-06      0.482      0.635   -2.27e-06    3.65e-06
==============================================================================
Omnibus:                       13.324   Durbin-Watson:                   2.253
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               23.238
Skew:                           0.818   Prob(JB):                     8.99e-06
Kurtosis:                       7.069   Cond. No.                     3.45e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.45e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

--- Brazil ---
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.865
Model:                            OLS   Adj. R-squared:                  0.828
Method:                 Least Squares   F-statistic:                     23.45
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.66e-08
Time:                        14:57:21   Log-Likelihood:                 39.601
No. Observations:                  29   AIC:                            -65.20
Df Residuals:                      22   BIC:                            -55.63
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -0.0400      0.096     -0.416      0.681      -0.240       0.159
household_income   7.375e-05   1.42e-05      5.192      0.000    4.43e-05       0.000
unemployment_rate     0.0032      0.009      0.344      0.734      -0.016       0.022
poverty_rate         -0.1142      0.080     -1.429      0.167      -0.280       0.052
inflation          1.853e-05   4.39e-05      0.422      0.677   -7.26e-05       0.000
imports            3.673e-08   1.41e-06      0.026      0.979   -2.89e-06    2.96e-06
exports            5.748e-07   1.69e-06      0.340      0.737   -2.93e-06    4.08e-06
==============================================================================
Omnibus:                        1.953   Durbin-Watson:                   1.938
Prob(Omnibus):                  0.377   Jarque-Bera (JB):                0.956
Skew:                          -0.411   Prob(JB):                        0.620
Kurtosis:                       3.338   Cond. No.                     3.15e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.15e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

--- Colombia ---
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.869
Method:                 Least Squares   F-statistic:                     31.82
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           9.15e-10
Time:                        14:57:21   Log-Likelihood:                 51.505
No. Observations:                  29   AIC:                            -89.01
Df Residuals:                      22   BIC:                            -79.44
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0402      0.014      2.839      0.010       0.011       0.069
household_income      0.0002   1.84e-05      8.411      0.000       0.000       0.000
unemployment_rate     0.0034      0.009      0.360      0.722      -0.016       0.023
poverty_rate          0.0107      0.028      0.376      0.710      -0.048       0.070
inflation             0.0019      0.005      0.408      0.687      -0.008       0.012
imports           -9.632e-07   3.42e-06     -0.282      0.781   -8.05e-06    6.13e-06
exports           -1.943e-06   3.16e-06     -0.615      0.545    -8.5e-06    4.61e-06
==============================================================================
Omnibus:                        0.406   Durbin-Watson:                   1.297
Prob(Omnibus):                  0.816   Jarque-Bera (JB):                0.549
Skew:                           0.092   Prob(JB):                        0.760
Kurtosis:                       2.352   Cond. No.                     3.36e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.36e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

--- Vietnam ---
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.645
Model:                            OLS   Adj. R-squared:                  0.548
Method:                 Least Squares   F-statistic:                     6.662
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           0.000401
Time:                        14:57:21   Log-Likelihood:                 53.947
No. Observations:                  29   AIC:                            -93.89
Df Residuals:                      22   BIC:                            -84.32
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0678      0.059      1.158      0.259      -0.054       0.189
household_income   8.981e-05   8.44e-05      1.064      0.299   -8.52e-05       0.000
unemployment_rate    -0.0107      0.023     -0.466      0.646      -0.059       0.037
poverty_rate         -0.0178      0.015     -1.211      0.239      -0.048       0.013
inflation             0.0070      0.002      3.512      0.002       0.003       0.011
imports            2.371e-06   1.95e-06      1.214      0.238   -1.68e-06    6.42e-06
exports           -3.361e-06   2.45e-06     -1.369      0.185   -8.45e-06    1.73e-06
==============================================================================
Omnibus:                        1.134   Durbin-Watson:                   1.297
Prob(Omnibus):                  0.567   Jarque-Bera (JB):                0.426
Skew:                           0.276   Prob(JB):                        0.808
Kurtosis:                       3.219   Cond. No.                     2.03e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.03e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

--- Germany ---
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.960
Model:                            OLS   Adj. R-squared:                  0.949
Method:                 Least Squares   F-statistic:                     88.06
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           3.02e-14
Time:                        14:57:21   Log-Likelihood:                 79.277
No. Observations:                  29   AIC:                            -144.6
Df Residuals:                      22   BIC:                            -135.0
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0050      0.004      1.303      0.206      -0.003       0.013
household_income   2.058e-05   2.04e-06     10.101      0.000    1.64e-05    2.48e-05

### Model Pruning - Selecting Best Predictors

In [31]:
def stepwise_model_polars(data: pl.DataFrame, target: str, predictors: list[str]):
    pdf = data.to_pandas()

    y = pdf[target]
    current_predictors = predictors.copy()

    while True:
        X = sm.add_constant(pdf[current_predictors])
        model = sm.OLS(y, X).fit()

        pvals = model.pvalues.drop("const", errors="ignore")
        max_p = pvals.max()

        if max_p > 0.05:
            worst_var = pvals.idxmax()
            current_predictors.remove(worst_var)
        else:
            break

    final_X = sm.add_constant(pdf[current_predictors])
    final_model = sm.OLS(y, final_X).fit()

    return final_model, current_predictors

In [33]:
final_models = {}
selected_predictors = {}

for country, data in transformed_country_data.items():
    final_model, kept_vars = stepwise_model_polars(
        data=data,
        target="gdp_growth_log",
        predictors=predictors
    )

    final_models[country] = final_model
    selected_predictors[country] = kept_vars

    print(f"\nFinal model for {country}")
    print("Selected predictors:", kept_vars)
    print(final_model.summary())

Final model for Mexico
Selected predictors: ['household_income', 'unemployment_rate', 'imports']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.916
Model:                            OLS   Adj. R-squared:                  0.906
Method:                 Least Squares   F-statistic:                     91.20
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.35e-13
Time:                        14:57:46   Log-Likelihood:                 55.684
No. Observations:                  29   AIC:                            -103.4
Df Residuals:                      25   BIC:                            -97.90
Df Model:                           3
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0182      0.008      2.257      0.033       0.002       0.035
household_income   7.412e-05   6.32e-06     11.737      0.000    6.11e-05    8.71e-05
unemployment_rate    -0.0357      0.014     -2.620      0.015      -0.064      -0.008
imports           -7.556e-07   2.99e-07     -2.530      0.018   -1.37e-06    -1.4e-07
==============================================================================
Omnibus:                        1.566   Durbin-Watson:                   1.891
Prob(Omnibus):                  0.457   Jarque-Bera (JB):                1.309
Skew:                           0.349   Prob(JB):                        0.520
Kurtosis:                       2.228   Cond. No.                     8.23e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.23e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Final model for Egypt
Selected predictors: ['household_income', 'poverty_rate']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.851
Model:                            OLS   Adj. R-squared:                  0.839
Method:                 Least Squares   F-statistic:                     74.01
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.85e-11
Time:                        14:57:46   Log-Likelihood:                 46.952
No. Observations:                  29   AIC:                            -87.90
Df Residuals:                      26   BIC:                            -83.80
Df Model:                           2
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0272      0.011      2.572      0.016       0.005       0.049
household_income     0.0001   1.18e-05     10.908      0.000       0.000       0.000
poverty_rate        -0.1500      0.053     -2.853      0.008      -0.258      -0.042
==============================================================================
Omnibus:                        0.692   Durbin-Watson:                   1.570
Prob(Omnibus):                  0.708   Jarque-Bera (JB):                0.702
Skew:                           0.104   Prob(JB):                        0.704
Kurtosis:                       2.267   Cond. No.                     4.81e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.81e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Final model for Czech Republic
Selected predictors: ['household_income']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.687
Model:                            OLS   Adj. R-squared:                  0.675
Method:                 Least Squares   F-statistic:                     59.25
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           2.80e-08
Time:                        14:57:46   Log-Likelihood:                 41.574
No. Observations:                  29   AIC:                            -79.15
Df Residuals:                      27   BIC:                            -76.41
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0202      0.013      1.592      0.123      -0.006       0.046
household_income  4.776e-05    6.2e-06      7.697      0.000     3.5e-05    6.05e-05
==============================================================================
Omnibus:                        2.158   Durbin-Watson:                   0.844
Prob(Omnibus):                  0.340   Jarque-Bera (JB):                1.822
Skew:                           0.490   Prob(JB):                        0.402
Kurtosis:                       2.259   Cond. No.                     2.35e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.35e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Final model for Canada
Selected predictors: ['household_income', 'poverty_rate', 'exports']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.905
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     79.56
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           6.38e-13
Time:                        14:57:46   Log-Likelihood:                 66.606
No. Observations:                  29   AIC:                            -125.2
Df Residuals:                      25   BIC:                            -119.7
Df Model:                           3
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0062      0.006      1.021      0.317      -0.006       0.019
household_income  1.542e-05   2.48e-06      6.227      0.000    1.03e-05    2.05e-05
poverty_rate        -0.3058      0.117     -2.607      0.015      -0.547      -0.064
exports           8.926e-07    1.4e-07      6.396      0.000    6.05e-07    1.18e-06
==============================================================================
Omnibus:                        4.904   Durbin-Watson:                   1.669
Prob(Omnibus):                  0.086   Jarque-Bera (JB):                3.188
Skew:                          -0.651   Prob(JB):                        0.203
Kurtosis:                       3.972   Cond. No.                     1.20e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.2e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

Final model for South Africa
Selected predictors: ['household_income']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.923
Model:                            OLS   Adj. R-squared:                  0.921
Method:                 Least Squares   F-statistic:                     325.3
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.38e-16
Time:                        14:57:46   Log-Likelihood:                 55.928
No. Observations:                  29   AIC:                            -107.9
Df Residuals:                      27   BIC:                            -105.1
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0335      0.007      4.955      0.000       0.020       0.047
household_income     0.0002   9.06e-06     18.035      0.000       0.000       0.000
==============================================================================
Omnibus:                       20.880   Durbin-Watson:                   1.939
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               53.864
Skew:                           1.240   Prob(JB):                     2.01e-12
Kurtosis:                       9.199   Cond. No.                         747.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Final model for Brazil
Selected predictors: ['household_income', 'poverty_rate']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.857
Model:                            OLS   Adj. R-squared:                  0.846
Method:                 Least Squares   F-statistic:                     77.71
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.08e-11
Time:                        14:57:46   Log-Likelihood:                 38.760
No. Observations:                  29   AIC:                            -71.52
Df Residuals:                      26   BIC:                            -67.42
Df Model:                           2
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0006      0.016      0.035      0.972      -0.032       0.033
household_income  8.044e-05   8.51e-06      9.453      0.000    6.29e-05    9.79e-05
poverty_rate        -0.1002      0.048     -2.085      0.047      -0.199      -0.001
==============================================================================
Omnibus:                        0.202   Durbin-Watson:                   1.959
Prob(Omnibus):                  0.904   Jarque-Bera (JB):                0.257
Skew:                          -0.173   Prob(JB):                        0.879
Kurtosis:                       2.694   Cond. No.                     6.83e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.83e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Final model for Colombia
Selected predictors: ['household_income']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.888
Model:                            OLS   Adj. R-squared:                  0.884
Method:                 Least Squares   F-statistic:                     214.3
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           2.32e-14
Time:                        14:57:46   Log-Likelihood:                 50.345
No. Observations:                  29   AIC:                            -96.69
Df Residuals:                      27   BIC:                            -93.96
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0346      0.008      4.160      0.000       0.018       0.052
household_income     0.0001   9.14e-06     14.638      0.000       0.000       0.000
==============================================================================
Omnibus:                        0.793   Durbin-Watson:                   1.108
Prob(Omnibus):                  0.673   Jarque-Bera (JB):                0.772
Skew:                           0.154   Prob(JB):                        0.680
Kurtosis:                       2.263   Cond. No.                         919.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Final model for Vietnam
Selected predictors: ['poverty_rate', 'inflation']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.609
Model:                            OLS   Adj. R-squared:                  0.579
Method:                 Least Squares   F-statistic:                     20.24
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           5.02e-06
Time:                        14:57:46   Log-Likelihood:                 52.541
No. Observations:                  29   AIC:                            -99.08
Df Residuals:                      26   BIC:                            -94.98
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.0295      0.017      1.782      0.086      -0.005       0.063
poverty_rate    -0.0242      0.011     -2.108      0.045      -0.048      -0.001
inflation        0.0087      0.001      6.018      0.000       0.006       0.012
==============================================================================
Omnibus:                        1.598   Durbin-Watson:                   1.193
Prob(Omnibus):                  0.450   Jarque-Bera (JB):                0.564
Skew:                           0.209   Prob(JB):                        0.754
Kurtosis:                       3.540   Cond. No.                         20.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Final model for Germany
Selected predictors: ['household_income', 'inflation', 'exports']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.957
Model:                            OLS   Adj. R-squared:                  0.952
Method:                 Least Squares   F-statistic:                     185.1
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           3.42e-17
Time:                        14:57:47   Log-Likelihood:                 78.191
No. Observations:                  29   AIC:                            -148.4
Df Residuals:                      25   BIC:                            -142.9
Df Model:                           3
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0038      0.004      1.089      0.286      -0.003       0.011
household_income   2.02e-05   1.74e-06     11.614      0.000    1.66e-05    2.38e-05
inflation           -0.0107      0.003     -3.386      0.002      -0.017      -0.004
exports           1.743e-07   5.06e-08      3.446      0.002    7.01e-08    2.78e-07
==============================================================================
Omnibus:                        0.393   Durbin-Watson:                   1.871
Prob(Omnibus):                  0.822   Jarque-Bera (JB):                0.544
Skew:                          -0.120   Prob(JB):                        0.762
Kurtosis:                       2.373   Cond. No.                     1.38e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.38e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

Final model for India
Selected predictors: ['household_income', 'imports']
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.697
Model:                            OLS   Adj. R-squared:                  0.673
Method:                 Least Squares   F-statistic:                     29.88
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.83e-07
Time:                        14:57:47   Log-Likelihood:                 53.490
No. Observations:                  29   AIC:                            -101.0
Df Residuals:                      26   BIC:                            -96.88
Df Model:                           2
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0374      0.010      3.769      0.001       0.017       0.058
household_income     0.0003   5.58e-05      5.684      0.000       0.000       0.000
imports          -5.451e-07   2.33e-07     -2.342      0.027   -1.02e-06   -6.67e-08
==============================================================================
Omnibus:                        3.597   Durbin-Watson:                   1.057
Prob(Omnibus):                  0.166   Jarque-Bera (JB):                1.644
Skew:                           0.212   Prob(JB):                        0.440
Kurtosis:                       1.914   Cond. No.                     9.18e+04
==============================================================================

Notes:

## Heteroskedasticity

In [34]:
heteroskedasticity_results = []

for country, model in final_models.items():
    bp = het_breuschpagan(model.resid, model.model.exog)
    white = het_white(model.resid, model.model.exog)

    heteroskedasticity_results.append({
        "country": country,
        "bp_lm_stat": bp[0],
        "bp_p_value": bp[1],
        "white_lm_stat": white[0],
        "white_p_value": white[1]
    })

heteroskedasticity_df = pl.DataFrame(heteroskedasticity_results)
print(heteroskedasticity_df)

shape: (10, 5)
┌────────────────┬────────────┬────────────┬───────────────┬───────────────┐
│ country        ┆ bp_lm_stat ┆ bp_p_value ┆ white_lm_stat ┆ white_p_value │
│ ---            ┆ ---        ┆ ---        ┆ ---           ┆ ---           │
│ str            ┆ f64        ┆ f64        ┆ f64           ┆ f64           │
╞════════════════╪════════════╪════════════╪═══════════════╪═══════════════╡
│ Mexico         ┆ 4.687482   ┆ 0.196165   ┆ 14.910169     ┆ 0.093433      │
│ Egypt          ┆ 4.240535   ┆ 0.12       ┆ 12.834635     ┆ 0.024979      │
│ Czech Republic ┆ 2.520897   ┆ 0.112347   ┆ 2.739758      ┆ 0.254138      │
│ Canada         ┆ 4.91547    ┆ 0.178092   ┆ 16.97761      ┆ 0.030343      │
│ South Africa   ┆ 8.182954   ┆ 0.004229   ┆ 14.889373     ┆ 0.000585      │
│ Brazil         ┆ 4.860831   ┆ 0.088      ┆ 6.692774      ┆ 0.24451       │
│ Colombia       ┆ 6.573758   ┆ 0.010349   ┆ 7.431913      ┆ 0.024332      │
│ Vietnam        ┆ 1.336796   ┆ 0.512529   ┆ 6.384592      ┆ 0.270574      │
│ Germany        ┆ 0.275853   ┆ 0.964504   ┆ 17.572533     ┆ 0.04047       │
│ India          ┆ 5.599371   ┆ 0.060829   ┆ 7.495278      ┆ 0.186333      │
└────────────────┴────────────┴────────────┴───────────────┴───────────────┘

In [35]:
robust_models = {}

for country, model in final_models.items():
    robust_models[country] = model.get_robustcov_results(cov_type="HC1")

    print(f"\nRobust model for {country}")
    print(robust_models[country].summary())

Robust model for Mexico
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.916
Model:                            OLS   Adj. R-squared:                  0.906
Method:                 Least Squares   F-statistic:                     77.10
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           9.07e-13
Time:                        14:58:43   Log-Likelihood:                 55.684
No. Observations:                  29   AIC:                            -103.4
Df Residuals:                      25   BIC:                            -97.90
Df Model:                           3
Covariance Type:                  HC1
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 0.0182      0.007      2.617      0.015       0.004       0.032
household_income   7.412e-05   8.29e-06      8.944      0.000    5.71e-05    9.12e-05
unemployment_rate    -0.0357      0.013     -2.724      0.012      -0.063      -0.009
imports           -7.556e-07   3.66e-07     -2.065      0.049   -1.51e-06   -1.95e-09
==============================================================================
Omnibus:                        1.566   Durbin-Watson:                   1.891
Prob(Omnibus):                  0.457   Jarque-Bera (JB):                1.309
Skew:                           0.349   Prob(JB):                        0.520
Kurtosis:                       2.228   Cond. No.                     8.23e+04
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 8.23e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Robust model for Egypt
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.851
Model:                            OLS   Adj. R-squared:                  0.839
Method:                 Least Squares   F-statistic:                     63.88
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           9.24e-11
Time:                        14:58:43   Log-Likelihood:                 46.952
No. Observations:                  29   AIC:                            -87.90
Df Residuals:                      26   BIC:                            -83.80
Df Model:                           2
Covariance Type:                  HC1
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0272      0.012      2.320      0.028       0.003       0.051
household_income     0.0001   1.45e-05      8.859      0.000    9.85e-05       0.000
poverty_rate        -0.1500      0.055     -2.740      0.011      -0.263      -0.037
==============================================================================
Omnibus:                        0.692   Durbin-Watson:                   1.570
Prob(Omnibus):                  0.708   Jarque-Bera (JB):                0.702
Skew:                           0.104   Prob(JB):                        0.704
Kurtosis:                       2.267   Cond. No.                     4.81e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 4.81e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Robust model for Czech Republic
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.687
Model:                            OLS   Adj. R-squared:                  0.675
Method:                 Least Squares   F-statistic:                     64.73
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.21e-08
Time:                        14:58:43   Log-Likelihood:                 41.574
No. Observations:                  29   AIC:                            -79.15
Df Residuals:                      27   BIC:                            -76.41
Df Model:                           1
Covariance Type:                  HC1
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0202      0.011      1.906      0.067      -0.002       0.042
household_income  4.776e-05   5.94e-06      8.045      0.000    3.56e-05    5.99e-05
==============================================================================
Omnibus:                        2.158   Durbin-Watson:                   0.844
Prob(Omnibus):                  0.340   Jarque-Bera (JB):                1.822
Skew:                           0.490   Prob(JB):                        0.402
Kurtosis:                       2.259   Cond. No.                     2.35e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.35e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Robust model for Canada
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.905
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     112.5
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.21e-14
Time:                        14:58:43   Log-Likelihood:                 66.606
No. Observations:                  29   AIC:                            -125.2
Df Residuals:                      25   BIC:                            -119.7
Df Model:                           3
Covariance Type:                  HC1
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0062      0.006      1.116      0.275      -0.005       0.018
household_income  1.542e-05   3.53e-06      4.370      0.000    8.15e-06    2.27e-05
poverty_rate        -0.3058      0.119     -2.575      0.016      -0.550      -0.061
exports           8.926e-07   2.28e-07      3.913      0.001    4.23e-07    1.36e-06
==============================================================================
Omnibus:                        4.904   Durbin-Watson:                   1.669
Prob(Omnibus):                  0.086   Jarque-Bera (JB):                3.188
Skew:                          -0.651   Prob(JB):                        0.203
Kurtosis:                       3.972   Cond. No.                     1.20e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.2e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

Robust model for South Africa
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.923
Model:                            OLS   Adj. R-squared:                  0.921
Method:                 Least Squares   F-statistic:                     91.31
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           3.73e-10
Time:                        14:58:43   Log-Likelihood:                 55.928
No. Observations:                  29   AIC:                            -107.9
Df Residuals:                      27   BIC:                            -105.1
Df Model:                           1
Covariance Type:                  HC1
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0335      0.007      5.043      0.000       0.020       0.047
household_income     0.0002   1.71e-05      9.556      0.000       0.000       0.000
==============================================================================
Omnibus:                       20.880   Durbin-Watson:                   1.939
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               53.864
Skew:                           1.240   Prob(JB):                     2.01e-12
Kurtosis:                       9.199   Cond. No.                         747.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)

Robust model for Brazil
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.857
Model:                            OLS   Adj. R-squared:                  0.846
Method:                 Least Squares   F-statistic:                     51.19
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           9.64e-10
Time:                        14:58:43   Log-Likelihood:                 38.760
No. Observations:                  29   AIC:                            -71.52
Df Residuals:                      26   BIC:                            -67.42
Df Model:                           2
Covariance Type:                  HC1
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0006      0.014      0.039      0.969      -0.029       0.030
household_income  8.044e-05   9.78e-06      8.224      0.000    6.03e-05       0.000
poverty_rate        -0.1002      0.029     -3.476      0.002      -0.159      -0.041
==============================================================================
Omnibus:                        0.202   Durbin-Watson:                   1.959
Prob(Omnibus):                  0.904   Jarque-Bera (JB):                0.257
Skew:                          -0.173   Prob(JB):                        0.879
Kurtosis:                       2.694   Cond. No.                     6.83e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 6.83e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Robust model for Colombia
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.888
Model:                            OLS   Adj. R-squared:                  0.884
Method:                 Least Squares   F-statistic:                     219.9
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.70e-14
Time:                        14:58:43   Log-Likelihood:                 50.345
No. Observations:                  29   AIC:                            -96.69
Df Residuals:                      27   BIC:                            -93.96
Df Model:                           1
Covariance Type:                  HC1
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0346      0.008      4.551      0.000       0.019       0.050
household_income     0.0001   9.03e-06     14.830      0.000       0.000       0.000
==============================================================================
Omnibus:                        0.793   Durbin-Watson:                   1.108
Prob(Omnibus):                  0.673   Jarque-Bera (JB):                0.772
Skew:                           0.154   Prob(JB):                        0.680
Kurtosis:                       2.263   Cond. No.                         919.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)

Robust model for Vietnam
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.609
Model:                            OLS   Adj. R-squared:                  0.579
Method:                 Least Squares   F-statistic:                     31.77
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           1.04e-07
Time:                        14:58:43   Log-Likelihood:                 52.541
No. Observations:                  29   AIC:                            -99.08
Df Residuals:                      26   BIC:                            -94.98
Df Model:                           2
Covariance Type:                  HC1
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.0295      0.013      2.276      0.031       0.003       0.056
poverty_rate    -0.0242      0.011     -2.176      0.039      -0.047      -0.001
inflation        0.0087      0.001      6.810      0.000       0.006       0.011
==============================================================================
Omnibus:                        1.598   Durbin-Watson:                   1.193
Prob(Omnibus):                  0.450   Jarque-Bera (JB):                0.564
Skew:                           0.209   Prob(JB):                        0.754
Kurtosis:                       3.540   Cond. No.                         20.2
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)

Robust model for Germany
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.957
Model:                            OLS   Adj. R-squared:                  0.952
Method:                 Least Squares   F-statistic:                     116.1
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           8.36e-15
Time:                        14:58:43   Log-Likelihood:                 78.191
No. Observations:                  29   AIC:                            -148.4
Df Residuals:                      25   BIC:                            -142.9
Df Model:                           3
Covariance Type:                  HC1
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0038      0.004      1.081      0.290      -0.003       0.011
household_income   2.02e-05   2.23e-06      9.050      0.000    1.56e-05    2.48e-05
inflation           -0.0107      0.002     -4.344      0.000      -0.016      -0.006
exports           1.743e-07   4.23e-08      4.123      0.000    8.72e-08    2.61e-07
==============================================================================
Omnibus:                        0.393   Durbin-Watson:                   1.871
Prob(Omnibus):                  0.822   Jarque-Bera (JB):                0.544
Skew:                          -0.120   Prob(JB):                        0.762
Kurtosis:                       2.373   Cond. No.                     1.38e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.38e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

Robust model for India
                            OLS Regression Results
==============================================================================
Dep. Variable:         gdp_growth_log   R-squared:                       0.697
Model:                            OLS   Adj. R-squared:                  0.673
Method:                 Least Squares   F-statistic:                     45.35
Date:                Mon, 30 Mar 2026   Prob (F-statistic):           3.33e-09
Time:                        14:58:43   Log-Likelihood:                 53.490
No. Observations:                  29   AIC:                            -101.0
Df Residuals:                      26   BIC:                            -96.88
Df Model:                           2
Covariance Type:                  HC1
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0374      0.007      5.442      0.000       0.023       0.051
household_income     0.0003   5.55e-05      5.712      0.000       0.000       0.000
imports          -5.451e-07   2.55e-07     -2.140      0.042   -1.07e-06   -2.16e-08
==============================================================================
Omnibus:                        3.597   Durbin-Watson:                   1.057
Prob(Omnibus):                  0.166   Jarque-Bera (JB):                1.644
Skew:                           0.212   Prob(JB):                        0.440
Kurtosis:                       1.914   Cond. No.                     9.18e+04
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.18e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

## VIF

In [36]:
def calculate_vif_from_polars(data: pl.DataFrame, predictors: list[str]):
    pdf = data.select(predictors).to_pandas()
    X = sm.add_constant(pdf)

    vif_rows = []
    for i, col in enumerate(X.columns):
        vif_rows.append({
            "variable": col,
            "VIF": variance_inflation_factor(X.values, i)
        })

    return pl.DataFrame(vif_rows)

In [37]:
vif_results = {}

for country, data in transformed_country_data.items():
    kept_vars = selected_predictors[country]
    vif_table = calculate_vif_from_polars(data, kept_vars)
    vif_results[country] = vif_table

    print(f"\nVIF for {country}")
    print(vif_table)

VIF for Mexico
shape: (4, 2)
┌───────────────────┬──────────┐
│ variable          ┆ VIF      │
│ ---               ┆ ---      │
│ str               ┆ f64      │
╞═══════════════════╪══════════╡
│ const             ┆ 1.288588 │
│ household_income  ┆ 2.400929 │
│ unemployment_rate ┆ 1.308176 │
│ imports           ┆ 2.644231 │
└───────────────────┴──────────┘

VIF for Egypt
shape: (3, 2)
┌──────────────────┬──────────┐
│ variable         ┆ VIF      │
│ ---              ┆ ---      │
│ str              ┆ f64      │
╞══════════════════╪══════════╡
│ const            ┆ 1.26649  │
│ household_income ┆ 1.051011 │
│ poverty_rate     ┆ 1.051011 │
└──────────────────┴──────────┘

VIF for Czech Republic
shape: (2, 2)
┌──────────────────┬──────────┐
│ variable         ┆ VIF      │
│ ---              ┆ ---      │
│ str              ┆ f64      │
╞══════════════════╪══════════╡
│ const            ┆ 1.311787 │
│ household_income ┆ 1.0      │
└──────────────────┴──────────┘

VIF for Canada
shape: (4, 2)
┌──────────────────┬──────────┐
│ variable         ┆ VIF      │
│ ---              ┆ ---      │
│ str              ┆ f64      │
╞══════════════════╪══════════╡
│ const            ┆ 1.536904 │
│ household_income ┆ 1.786386 │
│ poverty_rate     ┆ 1.063279 │
│ exports          ┆ 1.83669  │
└──────────────────┴──────────┘

VIF for South Africa
shape: (2, 2)
┌──────────────────┬─────────┐
│ variable         ┆ VIF     │
│ ---              ┆ ---     │
│ str              ┆ f64     │
╞══════════════════╪═════════╡
│ const            ┆ 1.00013 │
│ household_income ┆ 1.0     │
└──────────────────┴─────────┘

VIF for Brazil
shape: (3, 2)
┌──────────────────┬──────────┐
│ variable         ┆ VIF      │
│ ---              ┆ ---      │
│ str              ┆ f64      │
╞══════════════════╪══════════╡
│ const            ┆ 1.648896 │
│ household_income ┆ 1.362767 │
│ poverty_rate     ┆ 1.362767 │
└──────────────────┴──────────┘

VIF for Colombia
shape: (2, 2)
┌──────────────────┬──────────┐
│ variable         ┆ VIF      │
│ ---              ┆ ---      │
│ str              ┆ f64      │
╞══════════════════╪══════════╡
│ const            ┆ 1.024643 │
│ household_income ┆ 1.0      │
└──────────────────┴──────────┘

VIF for Vietnam
shape: (3, 2)
┌──────────────┬──────────┐
│ variable     ┆ VIF      │
│ ---          ┆ ---      │
│ str          ┆ f64      │
╞══════════════╪══════════╡
│ const        ┆ 4.547744 │
│ poverty_rate ┆ 1.000056 │
│ inflation    ┆ 1.000056 │
└──────────────┴──────────┘

VIF for Germany
shape: (4, 2)
┌──────────────────┬──────────┐
│ variable         ┆ VIF      │
│ ---              ┆ ---      │
│ str              ┆ f64      │
╞══════════════════╪══════════╡
│ const            ┆ 1.1575   │
│ household_income ┆ 2.668826 │
│ inflation        ┆ 1.515036 │
│ exports          ┆ 3.340986 │
└──────────────────┴──────────┘

VIF for India
shape: (3, 2)
┌──────────────────┬──────────┐
│ variable         ┆ VIF      │
│ ---              ┆ ---      │
│ str              ┆ f64      │
╞══════════════════╪══════════╡
│ const            ┆ 1.744841 │
│ household_income ┆ 4.073391 │
│ imports          ┆ 4.073391 │
└──────────────────┴──────────┘

## Condition Index

In [ ]:
def condition_index_from_polars(data: pl.DataFrame, predictors: list[str]):
    pdf = data.select(predictors).to_pandas().dropna()

    Z = (pdf - pdf.mean()) / pdf.std(ddof=0)
    Z = Z.loc[:, Z.std(ddof=0) > 0]
    X = Z.values

    eigvals = np.linalg.eigvals(X.T @ X)
    eigvals = np.real(eigvals)
    cond_idx = np.sqrt(eigvals.max() / eigvals)

    result = pl.DataFrame({
        "dimension": list(range(1, len(cond_idx) + 1)),
        "condition_index": cond_idx
    })

    return result

predictors = ["household_income", "unemployment_rate", "poverty_rate", "inflation", "imports", "exports"]
condition_index_from_polars(data=clean_df, predictors=predictors)

In [39]:
condition_index_results = []

for country, data in transformed_country_data.items():
    kept_vars = selected_predictors[country]
    ci_values = condition_index_from_polars(data, kept_vars)

    condition_index_results.append({
        "country": country,
        "max_condition_index": float(np.max(ci_values))
    })

condition_index_df = pl.DataFrame(condition_index_results)
print(condition_index_df)

shape: (10, 2)
┌────────────────┬─────────────────────┐
│ country        ┆ max_condition_index │
│ ---            ┆ ---                 │
│ str            ┆ f64                 │
╞════════════════╪═════════════════════╡
│ Mexico         ┆ 82296.706659        │
│ Egypt          ┆ 4813.551307         │
│ Czech Republic ┆ 2347.576701         │
│ Canada         ┆ 1.2011e6            │
│ South Africa   ┆ 746.985384          │
│ Brazil         ┆ 6834.209647         │
│ Colombia       ┆ 919.452516          │
│ Vietnam        ┆ 20.213963           │
│ Germany        ┆ 138444.236549       │
│ India          ┆ 91757.171733        │
└────────────────┴─────────────────────┘

In [60]:
anova_results = {}

for country, model in final_models.items():
    try:
        anova_table = anova_lm(model)
        anova_results[country] = anova_table
        print(f"\nANOVA for {country}")
        print(anova_table)
    except Exception as e:
        print(f"ANOVA not available for {country}: {e}")

ANOVA not available for Germany: 'PandasData' object has no attribute 'design_info'
ANOVA not available for Brazil: 'PandasData' object has no attribute 'design_info'
ANOVA not available for Czech Republic: 'PandasData' object has no attribute 'design_info'
ANOVA not available for Colombia: 'PandasData' object has no attribute 'design_info'
ANOVA not available for Egypt: 'PandasData' object has no attribute 'design_info'
ANOVA not available for India: 'PandasData' object has no attribute 'design_info'
ANOVA not available for Canada: 'PandasData' object has no attribute 'design_info'
ANOVA not available for Vietnam: 'PandasData' object has no attribute 'design_info'
ANOVA not available for South Africa: 'PandasData' object has no attribute 'design_info'
ANOVA not available for Mexico: 'PandasData' object has no attribute 'design_info'